Crossmint/crossmint-sdk

- packages/ui/react-ui/src/CrossMintPopupProvider.tsx
Introduced in https://github.com/CrossMint/crossmint-client-sdk/commit/2492fd956ab55335b7b9f2d85a71aa6b67615697#diff-466e95a585015ed84d1c70cab5d29696797e85598a715679a8620c323aad1c9e
> FIX: Missing & on callbackUrl

- packages/ui/react-ui/src/CrossMintButton.tsx
> Ignore default title, photo, desc

- packages/ui/react-ui/src/CrossMintStatusButton.tsx
> Typo on CrossMingStatusButton

- README.md
We should merge this once 0.1.0 is ready
> Revert "Temporary fix to ensure docs work for 0.0.8-alpha4"

- packages/ui/react-ui/src/CrossmintPayButton.tsx
- packages/ui/react-ui/src/CrossmintStatusButton.tsx
- packages/ui/react-ui/src/types.ts
`theme` prop is not working correctly ATM. You would need to pass theme enum. Better to use a type like this.
Also:
- Checking that `className` prop exists. Otherwise the dom is adding the class `undefined`.
> Allow light and dark strings on theme prop

- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
- packages/ui/react-ui/src/CrossmintPayButton.tsx
- packages/ui/react-ui/src/hooks/useCrossmintStatus.ts
> #40 request status only when hideMinOnInativeClient

- packages/ui/react-ui/src/CrossmintPayButton.tsx
Fix needed for Beyond Street Cred polygon drop
> Fix useCallback deps

- packages/core/base/package.json
- packages/starter/example/package.json
- packages/starter/nextjs-starter/package.json
- packages/starter/react-ui-starter/package.json
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/version.ts
- @crossmint/client-sdk-base@0.1.0-alpha.1
- @crossmint/client-sdk-example@0.1.0-alpha.5
- @crossmint/client-sdk-nextjs-starter@0.1.0-alpha.5
- @crossmint/client-sdk-react-ui-starter@0.1.0-alpha.5
- @crossmint/client-sdk-react-ui@0.1.4-alpha.1
> v0.1.4-alpha.1

- packages/core/base/package.json
- packages/starter/example/package.json
- packages/starter/nextjs-starter/package.json
- packages/starter/react-ui-starter/package.json
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/version.ts
- @crossmint/client-sdk-base@0.1.0-alpha.2
- @crossmint/client-sdk-example@0.1.0-alpha.6
- @crossmint/client-sdk-nextjs-starter@0.1.0-alpha.6
- @crossmint/client-sdk-react-ui-starter@0.1.0-alpha.6
- @crossmint/client-sdk-react-ui@0.1.4-alpha.2
> v0.1.4-alpha.2

- packages/core/base/src/services/crossmintStatusService.ts
- packages/core/base/src/utils/validateUUID.ts
- packages/starter/vanilla-ui-starter/index.html
- packages/ui/vanilla-ui/package.json
- packages/ui/vanilla-ui/src/CrossmintPayButton.ts
Now, with this new bundle, Vanilla UI `crossmint-pay-button` will work in ES6 environments, Common JS environments, but also in the browser via CDN! See the new `vanilla-ui-starter/index.html` 😄
> New bundle to Vanilla UI button

- packages/core/base/src/index.ts
- packages/core/base/src/services/crossmintStatusButtonService.ts
- packages/core/base/src/services/crossmintStatusService.ts
- packages/ui/react-ui/src/CrossmintStatusButton.tsx
- packages/ui/vanilla-ui/src/CrossmintStatusButton.ts
- packages/ui/vanilla-ui/src/index.ts
- packages/ui/vanilla-ui/src/types.ts
Create status button on Vanilla UI
> Create vanilla status button

- packages/core/base/package.json
- packages/starter/example/package.json
- packages/starter/nextjs-starter/package.json
- packages/starter/react-ui-starter/package.json
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/version.ts
- packages/ui/vanilla-ui/package.json
- packages/ui/vanilla-ui/src/version.ts
- @crossmint/client-sdk-base@0.1.1-alpha.2
- @crossmint/client-sdk-example@0.1.1-alpha.2
- @crossmint/client-sdk-nextjs-starter@0.1.1-alpha.2
- @crossmint/client-sdk-react-ui-starter@0.1.1-alpha.2
- @crossmint/client-sdk-react-ui@0.1.5-alpha.2
- @crossmint/client-sdk-vanilla-ui@0.0.1-alpha.2
> Release 2022-04-16

- packages/core/base/src/models/types.ts
- packages/core/base/src/services/crossmintModalService.ts
- packages/core/base/src/services/crossmintPayButtonService.ts
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
- packages/ui/react-ui/src/CrossmintPayButton.tsx
- packages/ui/vanilla-ui/src/CrossmintPayButton.ts
Changes requested in https://docs.google.com/document/d/1vOlaBfIeaPA1TwstwGH4ey9F2bgQ8UT1bjpvrKFSt6g/edit#
> Pay with ETH

- packages/core/base/src/services/crossmintModalService.ts
- packages/starter/vanilla-ui-starter/index.html
See https://github.com/Crossmint/crossmint-client-sdk/pull/103#issuecomment-1119380838
> Extra safety on popup not opening

- packages/ui/vanilla-ui/src/CrossmintPayButton.ts
- packages/ui/vanilla-ui/src/CrossmintStatusButton.ts
Disabled wasn't working on the vanilla UI buttons. Now it is
> Fix vanilla UI disabled state

- packages/core/base/src/models/types.ts
- packages/core/base/src/services/crossmintModalService.ts
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
- packages/ui/react-ui/src/CrossmintPayButton.tsx
- packages/ui/vanilla-ui/src/CrossmintPayButton.ts
Added `preferredSigninMethod` prop. This will be used wether to render the new signin form.
> Add preferredSigninMethod prop

- packages/core/base/package.json
- packages/starter/example/package.json
- packages/starter/nextjs-starter/package.json
- packages/starter/react-ui-starter/package.json
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/version.ts
- packages/ui/vanilla-ui/package.json
- packages/ui/vanilla-ui/src/version.ts
- @crossmint/client-sdk-base@0.1.2-alpha.3
- @crossmint/client-sdk-example@0.1.2-alpha.3
- @crossmint/client-sdk-nextjs-starter@0.1.2-alpha.3
- @crossmint/client-sdk-react-ui-starter@0.1.2-alpha.3
- @crossmint/client-sdk-react-ui@0.1.6-alpha.3
- @crossmint/client-sdk-vanilla-ui@0.0.2-alpha.3
> Release 2022/05/12

- packages/core/base/package.json
- packages/starter/example/package.json
- packages/starter/nextjs-starter/package.json
- packages/starter/react-ui-starter/package.json
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/version.ts
- packages/ui/vanilla-ui/package.json
- packages/ui/vanilla-ui/src/version.ts
- @crossmint/client-sdk-base@0.1.2
- @crossmint/client-sdk-example@0.1.2
- @crossmint/client-sdk-nextjs-starter@0.1.2
- @crossmint/client-sdk-react-ui-starter@0.1.2
- @crossmint/client-sdk-react-ui@0.1.6
- @crossmint/client-sdk-vanilla-ui@0.0.2
> Release 2022/05/13

- packages/core/base/src/models/types.ts
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
Adding preferred signin method -> Solana
> Preferred signin method solana

- packages/core/base/src/models/types.ts
- packages/core/base/src/services/crossmintPayButtonService.ts
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
> Add payment method SOL

- packages/core/base/src/services/crossmintModalService.ts
Makes centering when opening popup better, and abstracts popup dimensions
> Fix popup centering on window

- README.md
- packages/core/base/package.json
- packages/core/base/src/models/types.ts
- packages/core/base/src/services/crossmintModalService.ts
- packages/core/base/src/services/crossmintPayButtonService.ts
- packages/starter/example/pages/index.tsx
- packages/starter/nextjs-starter/pages/index.tsx
- packages/starter/react-ui-starter/src/App.js
- packages/starter/vanilla-ui-starter/index.html
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/CrossmintPayButton.tsx
- packages/ui/vanilla-ui/package.json
- packages/ui/vanilla-ui/src/CrossmintPayButton.ts
Prep for v0.2.0 release:
- remove collection metadata params
- add migration doc to readme
I have already submitted a change request to the docs as well to reflect these changes
> Prep for v0.2.0 release

- packages/core/base/src/services/crossmintModalService.ts
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
https://linear.app/crossmint/issue/ENG-1054/[oe]-[easy]-remove-or-implement-closeonsuccess-query-param
> Remove closeOnSuccess param

- packages/core/base/src/models/types.ts
- packages/core/base/src/services/crossmintModalService.ts
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
- packages/ui/react-ui/src/CrossmintPayButton.tsx
- packages/ui/vanilla-ui/src/CrossmintPayButton.ts
Add prepay prop to CrossmintPayButton
> Add prepay prop to CrossmintPayButton

- packages/core/base/package.json
- packages/starter/example/package.json
- packages/starter/nextjs-starter/package.json
- packages/starter/react-ui-starter/package.json
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/version.ts
- packages/ui/vanilla-ui/package.json
- packages/ui/vanilla-ui/src/version.ts
- @crossmint/client-sdk-base@0.2.2-alpha.0
- @crossmint/client-sdk-example@0.1.6-alpha.0
- @crossmint/client-sdk-nextjs-starter@0.1.6-alpha.0
- @crossmint/client-sdk-react-ui-starter@0.1.6-alpha.0
- @crossmint/client-sdk-react-ui@0.2.2-alpha.0
- @crossmint/client-sdk-vanilla-ui@0.1.2-alpha.0
> Release 2023-02-20

- packages/core/base/src/models/types.ts
Requested by X2y2 
https://crossmint.slack.com/archives/C04EB8GTGUE/p1677034955748719
> Enable multi-mint config by adding type

- packages/core/base/package.json
- packages/starter/example/package.json
- packages/starter/nextjs-starter/package.json
- packages/starter/react-ui-starter/package.json
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/version.ts
- packages/ui/vanilla-ui/package.json
- packages/ui/vanilla-ui/src/version.ts
- @crossmint/client-sdk-base@0.2.2-alpha.1
- @crossmint/client-sdk-example@0.1.6-alpha.1
- @crossmint/client-sdk-nextjs-starter@0.1.6-alpha.1
- @crossmint/client-sdk-react-ui-starter@0.1.6-alpha.1
- @crossmint/client-sdk-react-ui@0.2.2-alpha.1
- @crossmint/client-sdk-vanilla-ui@0.1.2-alpha.1
> Release 2023 24 02

- packages/core/base/src/models/types.ts
Adds AUD as valid currency type
> Adds AUD support

- packages/core/base/src/services/crossmintModalService.ts
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
Display the initial login screen with the correct i18n settings
> Include i18n settings in login

- packages/core/base/src/models/types.ts
- packages/core/base/src/utils/index.ts
- packages/core/base/src/utils/ui.ts
- packages/core/base/src/utils/validate.ts
- packages/ui/react-ui/__tests__/CrossmintCollectionView.spec.tsx
- packages/ui/react-ui/__tests__/CrossmintNFTDetail.spec.tsx
- packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
- packages/ui/react-ui/__tests__/CrossmintStatusButton.spec.tsx
- packages/ui/react-ui/src/CrossmintNFTCollectionView.tsx
- packages/ui/react-ui/src/CrossmintNFTDetail.tsx
- packages/ui/react-ui/src/index.ts
Moving Wallet UI components to react package and common utils to the common package
Tested in starters. It working alright
> Add wallet UI components

- packages/core/base/src/models/types.ts
- packages/core/base/src/utils/ui.ts
- packages/ui/react-ui/__tests__/CrossmintNFTDetail.spec.tsx
Adding new types for NFT interface as discussed in https://crossmint.slack.com/archives/C04TY75BDA7/p1678867834767079
This makes the experience pretty delightful IMO:
https://user-images.githubusercontent.com/20989060/225292813-6e4e0157-682b-4f11-95d5-a64009d317cf.mov
Notice how much code just good typing removes.
> Adding new NFT interface

- packages/core/base/src/models/types.ts
> GBP Support

- packages/core/base/src/index.ts
- packages/core/base/src/models/paymentElement.ts
- packages/core/base/src/models/types.ts
- packages/core/base/src/services/crossmintModalService.ts
- packages/core/base/src/services/crossmintPayButtonService.ts
Types for the new CrossmintPaymentElement component that will come soon
> Payment element types

- lerna.json
- packages/core/base/src/models/events.ts
- packages/core/base/src/models/paymentElement.ts
- packages/starter/vue-ui-starter/src/App.vue
- packages/ui/vue-ui/package.json
- packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue
- packages/ui/vue-ui/vite.config.ts
- yarn.lock
OK that was tough...
Added .d.ts files to the bundle so the typing works as expected:
Also started to add types to the button itself... that was a shit show aswell. See the code for more context
> Adding dts vue UI

- packages/core/base/src/models/paymentElement.ts
- packages/core/base/src/models/types.ts
Adjustments discussed in https://docs.google.com/document/d/13u0jGRGX7MXXMUQ8-spQITCzfVDUiORQcw1FuYue-2Y/edit#
> Adjustments API SDK

- packages/core/base/src/services/crossmintModalService.ts
- packages/ui/react-ui/src/CrossmintPayButton.tsx
- packages/ui/react-ui/src/CrossmintStatusButton.tsx
Should fix @pgarciaegido's issue
> Change component and mintConfig types

- packages/core/base/src/models/events.ts
- packages/core/base/src/models/paymentElement.ts
- packages/core/base/src/services/crossmintPaymentService.ts
- packages/core/base/src/services/useCrossmintEvents.ts
- packages/core/base/src/utils/payments.ts
- packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue
Changing a few types and adding the first draft of the useCrossmintEvents function
> Adding a first draft of the Crossmint events hook

- packages/core/base/src/models/paymentElement.ts
Adding missing payloads on minting events based on this doc https://docs.google.com/document/d/1eXzbVJQS87dO-7YLZfKHbXHMe9dOWNivgdoQ_Ix3kk8/edit#
> Add remaining payloads in events

- packages/core/base/src/models/paymentElement.ts
- packages/core/base/src/models/types.ts
- packages/core/base/src/services/crossmintPaymentService.ts
- packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue
> change mintArgs => mintConfig

- packages/core/base/src/services/useCrossmintEvents.ts
- packages/starter/vue-ui-starter/src/components/Minting.vue
- packages/starter/vue-ui-starter/src/components/PayWithCC.vue
- packages/ui/vue-ui/src/main.ts
Few improvements on the logics requested by @mPaella
Also handling end to end events in starter
> Improvements

- packages/core/base/src/services/useCrossmintEvents.ts
Everytime the browser history changes, interval is cleared.
https://user-images.githubusercontent.com/20989060/227595664-f3629df5-8f3d-4fd3-ab8b-157d07b776fe.mov
> Clear interval when history changes

- packages/starter/vanilla-ui-starter/paymentElement.html
- packages/ui/vanilla-ui/src/CrossmintPaymentElement.ts
- packages/ui/vanilla-ui/src/index.d.ts
- packages/ui/vanilla-ui/src/index.ts
Adding vanilla Crossmint Payment Element:
> Add vanilla Crossmint Payment Element component

- packages/core/base/src/models/paymentElement.ts
Based on the new models we decided
> New events payload types

- packages/starter/nextjs-starter/package.json
- packages/starter/nextjs-starter/pages/payment-element.tsx
- packages/ui/react-ui/src/CrossmintPaymentElement.tsx
- packages/ui/vanilla-ui/src/CrossmintPaymentElement.ts
Dynamically adjust height for Vanilla and React components:
https://user-images.githubusercontent.com/20989060/228875795-45d8cf07-9c52-4432-be8b-05da36da96ed.mov
> Dynamically adjust height on Vanilla and React payment components

- packages/ui/react-ui/__tests__/CrossmintPaymentElement.spec.tsx
- packages/ui/react-ui/package.json
- packages/ui/react-ui/src/CrossmintPaymentElement.tsx
- yarn.lock
Add a few unit tests to PaymentElement component
> Add test payment element

- packages/core/base/src/models/events.ts
- packages/core/base/src/models/paymentElement.ts
Context: https://docs.google.com/document/d/1iFKcC6Vtjc8YCyjGTJvt_w56n_PeAqjn9fEprBgTe2E/edit#
> Add transaction verification new events

- packages/core/base/src/services/crossmintPaymentService.ts
Passing locale to query params in payment element
> Pass locale to query params

- packages/core/base/src/models/events.ts
- packages/core/base/src/models/paymentElement.ts
Adding a new event when mint to wallet changes
> Adding wallet changed event

- packages/core/base/src/models/paymentElement.ts
> Add payment method type to payment rejected

- packages/core/base/src/models/paymentElement.ts
- packages/core/base/src/services/crossmintPaymentService.ts
- packages/ui/react-ui/__tests__/CrossmintPaymentElement.spec.tsx
- packages/ui/react-ui/src/CrossmintPaymentElement.tsx
- packages/ui/vanilla-ui/src/CrossmintPaymentElement.ts
- packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue
> Adding whPassThroughArgs field

- packages/core/base/src/models/fonts.ts
- packages/core/base/src/models/types.ts
Add an option to pass fonts to the uiConfig
> Extend UiConfig to include fonts

- packages/core/base/src/models/paymentElement.ts
- packages/core/base/src/services/crossmintPaymentService.ts
Adds ability to hide/show certain card wallet payment methods
> embed: Adds wallet payment methods options

- packages/core/base/src/services/crossmintModalService.ts
Catch bug with window.top and handle
> add window try/catch to fix bug in modal service 

- packages/core/base/src/services/crossmintStatusService.ts
- packages/ui/react-ui/src/CrossmintPayButton.tsx
Remove more unused stuff for new version
> Remove some more unused onboarding stuff

- packages/ui/vanilla-ui/src/CrossmintPaymentElement.ts
- packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue
Passing projectId prop to vanilla payment element SDK
> Pass ProjectId to vanilla payment element

- packages/ui/vanilla-ui/src/CrossmintPayButton.ts
- packages/ui/vanilla-ui/src/CrossmintPaymentElement.ts
- yarn.lock
> Fix types on Vanilla SDKs

- packages/ui/react-ui/src/CrossmintPayButton.tsx
Fixes bug, where button text would update, due to not re-rendering on change
> pay button: update useMemo on getButtonText change

- packages/core/base/src/models/events.ts
- packages/core/base/src/models/paymentElement.ts
- packages/core/base/src/services/crossmintModalService.ts
- packages/core/base/src/services/crossmintPaymentService.ts
- packages/core/base/src/services/useCrossmintEvents.ts
- packages/starter/vue-ui-starter/src/components/Minting.vue
- packages/starter/vue-ui-starter/src/components/PayWithCC.vue
- packages/ui/react-ui/src/CrossmintPaymentElement.tsx
- packages/ui/react-ui/src/index.ts
- packages/ui/vanilla-ui/src/CrossmintPaymentElement.ts
- packages/ui/vanilla-ui/src/index.ts
- packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue
- packages/ui/vue-ui/src/main.ts
Fixes bug for Sound.xyz
OLD:
NEW: payload is correctly inferred
> fix: onEvent type union

- packages/core/base/src/models/types.ts
> Add support for INR

- packages/core/base/src/models/paymentElement.ts
- packages/core/base/src/services/crossmintPaymentService.ts
- packages/ui/vanilla-ui/src/CrossmintPaymentElement.ts
- packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue
experimental feature to get email from apple/google pay
> embed: experimental use card wallet email

- packages/core/base/src/types/errors.ts
Error message to gate embedded checkout
> Add gated embedded checkout error

- packages/core/base/src/utils/embed/updatableParams.ts
> v1.1: fix emit params

- packages/starter/nextjs-starter/components/quote-summary.tsx
- packages/starter/nextjs-starter/pages/payment-element/eth.tsx
- packages/starter/nextjs-starter/pages/payment-element/sol.tsx
Point pay with crypto embedded demos to staging
> Point demos to staging

- packages/client/base/src/services/embed/crossmintIFrameService.ts
coerces collectionId to clientId properly
> embed(pay w crypto): collectionId => clientId

- packages/client/wallets/aa/src/CrossmintAASDK.ts
- packages/client/wallets/aa/src/api/CrossmintService.ts
- packages/client/wallets/aa/src/blockchain/wallets/BaseWallet.ts
- packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
- packages/client/wallets/aa/src/utils/error.ts
- Error control on the RPC messages response to capture 'physicalDeviceId' error.
- Handle earlier the 'Passphrase is required' check if is a new account.
- Clean code
> AA: Error control, order code, clean logs

- packages/client/wallets/aa/package.json
- yarn.lock
Using the new version of the ZeroDev SDK
> ZeroDev Version Updated

- packages/client/wallets/aa/src/CrossmintAASDK.ts
Deletes all the LocalStorage info which key starts with 'NCW-'
> WAL-1445: Purge wallet data

- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
Use the chain value to store int on the nonCustodialChainData. It was hardcoding 'polygon'
Set custodian data for a SCW and check on the database the value 'chain'
> WAL-1482: Use the value of the chain on the nonCustodialChainData

- packages/client/wallets/aa/src/CrossmintAASDK.ts
> aa: expose crossmintService

- packages/client/wallets/aa/src/CrossmintAASDK.ts
- packages/client/wallets/aa/src/api/CrossmintService.ts
- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
- packages/client/wallets/aa/src/utils/constants.ts
- packages/client/wallets/aa/src/utils/error.ts
If the chain is a testnet we return the staging URL, if the chain is a mainnet we return the prod URL.
> Depending on the network defined, connect to staging or prod

- packages/client/wallets/aa/src/ABI/ERC20.json
- packages/client/wallets/aa/src/blockchain/token/Tokens.ts
- packages/client/wallets/aa/src/blockchain/wallets/BaseWallet.ts
Added ERC20 ABI.
Added a new param 'amount' on the 'Transfer' method on the BaseWallet. If this param has info it will perform a ERC20 tx.
> WAL-1456: Add native token and ERC20 support for the transfer function in our SDK

- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/src/CrossmintAASDK.ts
- packages/client/wallets/aa/src/api/CrossmintService.ts
- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
- packages/client/wallets/aa/src/storage/PasswordEncryptedLocalStorage.ts
- packages/client/wallets/aa/src/types/Config.ts
- packages/client/wallets/aa/src/utils/auth.ts
- packages/client/wallets/aa/src/utils/constants.ts
- packages/client/wallets/aa/src/utils/index.ts
- packages/client/wallets/aa/src/utils/signer.ts
- yarn.lock
Added new signer type. Web3AuthSigner.  Using the following definition: 
export type Web3AuthSigner =  {
type: "WEB3_AUTH";
clientId: string; //Web3Auth Client ID
verifierId: string; //Web3Auth Verifier ID
jwt: string;
};
Attached screenshots to better understanding of the clientId and verifierId
Tested on scw_demo: 
https://github.com/Crossmint/crossmint-sdk/assets/131860331/21456187-00b4-4d8d-ba0c-18be1d553336
> WAL-1258: Added Web3AuthSigner

- packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
- packages/client/wallets/aa/src/storage/PasswordEncryptedLocalStorage.ts
- packages/client/wallets/aa/src/types/Config.ts
Passphrase mandatory and password for the localstorage
Create a SCW using Fireblocks NCW
> WAL-1472: Passphrase mandatory and password for the localstorage

- packages/client/wallets/aa/src/utils/signer.ts
Added the logic to get correctly the FireblocksNCW
> Fixed issue with isFireblocksNCW

- crossmint-sdk.code-workspace
- packages/client/verifiable-credentials/package.json
- packages/client/verifiable-credentials/src/index.ts
- packages/client/verifiable-credentials/src/presentation/getCredential.ts
- packages/client/verifiable-credentials/src/services/crossmintAPI.ts
- packages/client/verifiable-credentials/src/services/litInterface.ts
- packages/client/wallets/aa/package.json
- yarn.lock
Added getCredentialFromId to wrap the get credential API.
Added Lit network integration for automatic decryption of credentials for a given user.
Updated crossmintAPI to new standard.
> Credentials: Add retrieval and decryption

- packages/client/wallets/aa/src/api/CrossmintService.ts
- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
- packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
Add support for prod wallets
Tested pointing to my local server w/ prod keys
> add support for prod wallets

- packages/client/wallets/aa/src/services/logging/index.ts
- packages/client/wallets/aa/src/utils/constants.ts
Remove unused console log
Doesn't apply as it's just removing a console.log
> NCW: Remove unused console log

- package.json
- packages/client/wallets/aa/jest.config.ts
- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/src/CrossmintAASDK.test.ts
- packages/client/wallets/aa/src/api/CrossmintService.test.ts
- packages/client/wallets/aa/src/api/CrossmintService.ts
- packages/client/wallets/aa/src/blockchain/BlockchainNetwoks.test.ts
- packages/client/wallets/aa/src/utils/auth.test.ts
- packages/client/wallets/aa/src/utils/auth.ts
- packages/client/wallets/aa/src/utils/error.test.ts
- packages/client/wallets/aa/src/utils/error.ts
- packages/client/wallets/aa/src/utils/helpers.ts
- packages/client/wallets/aa/src/utils/index.ts
- packages/client/wallets/aa/src/utils/signer.test.ts
- yarn.lock
Added unit tests on Crossmint-SDK AA.
Coverage:  47.72% lines covered
yarn run test
yarn run test-coverage
> WAL-1486: Unit Tests

- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
- yarn.lock
Updated FB SDK version
Create AA Wallet
> WAL-1489: Update FB SDK version

- packages/common/base/src/index.ts
- packages/common/base/src/types/UserIdentifier.ts
- packages/common/base/src/types/index.ts
Added `UserIdentifier` and `UserIdentifierParams` at commons package related to this comment: 
https://github.com/Crossmint/crossmint-sdk/pull/337#discussion_r1445201040
Can be imported by client-sdk-aa
> SCW-81: Added UserIdentifier types at common package

- packages/client/wallets/aa/src/services/logging/index.ts
- packages/common/base/package.json
- packages/common/base/src/index.ts
- packages/common/base/src/types/blockchain.ts
- packages/common/base/src/types/index.ts
- packages/common/base/src/types/uiconfig.ts
Enums in base package
Manual testing
> Blockchain enums in base

- crossmint-sdk.code-workspace
- packages/client/verifiable-credentials/package.json
Verifiable credentials package to be renamed to @crossmint/client-sdk-verifiable-credentials
> VC: new package name

- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
- packages/client/wallets/aa/src/blockchain/wallets/CustomBridge.ts
- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
- packages/client/wallets/aa/src/blockchain/wallets/ZeroDevEip1193Bridge.ts
- packages/client/wallets/aa/src/types/Config.ts
- yarn.lock
getSigner("viem") using a custom bridge
Use
```
// Get Block Number
const blockNumber = await walletClient.getBlockNumber();
console.log(`Current Block Number: ${blockNumber}`);
// Sign a Message
const message = 'hello world';
const signature = await walletClient.signMessage({ message });
console.log(`Signed Message: ${signature}`);
// Verify the Signature
const signerAddress = ethers.utils.verifyMessage(message, signature);
console.log(`Signer Address: ${signerAddress}`);
// Get Balance
const address = '0x11d84BfB7243aB27DB3F4f2dcD1fD6d3Cc6f5E44'; 
const balance = await walletClient.getBalance({ address });
console.log(`Balance of ${address}: ${ethers.utils.formatEther(balance)} MATIC`);
// Get Addresses
const accounts = await walletClient.getAddresses();
console.log(`Wallet Addresses: …
```
> SCW-309: Added getSigner

- packages/client/verifiable-credentials/src/presentation/getCredential.ts
- packages/client/verifiable-credentials/src/presentation/getNfts.ts
- packages/client/verifiable-credentials/src/verification/services/signature.ts
- packages/client/verifiable-credentials/src/verification/verify.ts
Minor improvements:
- Moved to unstable api route
- Fixed did bug
- Improved verification on expiration date
- removed useless comments
> VC: cleanup

- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
- yarn.lock
Using the latest version of fireblocks ncw
Create AAWallet and mint
> SCW-361: Updated Fireblocks v11.0.1

- packages/client/base/src/types/embed/crypto.ts
Similar to https://github.com/Crossmint/crossmint-sdk/pull/358
Tested end to end with https://github.com/Paella-Labs/crossbit-main/pull/11375
> PayWithL2: Added 'supportedNetworks' parameter to pay with ETH

- packages/client/wallets/aa/src/utils/constants.ts
> update lit key

- packages/client/base/src/types/embed/crypto.ts
- packages/client/base/src/types/events/internal/events.ts
- packages/client/base/src/types/events/internal/payloads.ts
- packages/client/ui/react-ui/src/components/embed/crypto/CryptoEmbeddedCheckoutIFrame.tsx
Hopefully the last one 😅: https://crossmint.slack.com/archives/C06CV64AS6M/p1707611543544119
Smoke tested e2e integration
> PayWithL2: Re-renaming handleSwitchChain to handleChainSwitch

- packages/client/ui/react-ui/package.json
- packages/client/ui/vanilla-ui/package.json
- packages/client/ui/vue-ui/package.json
- packages/client/verifiable-credentials/package.json
- yarn.lock
Just bumping the version
yarn install works
> Bumping @crossmint/common-sdk-base to 1.1.6

- package.json
- packages/client/base/package.json
- packages/client/ui/react-ui/package.json
- packages/client/ui/vanilla-ui/package.json
- packages/client/verifiable-credentials/package.json
- packages/client/wallets/aa/package.json
- packages/client/window/package.json
- packages/common/base/package.json
- yarn.lock
adds dev (watch), scripts which auto rebuild when you save changes
adds cross-env so aa test script works on windows/all platforms
tested dev scripts work
ci
> dev ex: add dev scripts + cross-env

- packages/client/base/package.json
- packages/client/ui/react-ui/package.json
- packages/client/verifiable-credentials/package.json
- packages/client/wallets/aa/package.json
- packages/common/base/package.json
- yarn.lock
release 0.0.4 of common base
ci
> version: common-sdk-base 0.0.4

- packages/client/base/package.json
Missing from https://github.com/Crossmint/crossmint-sdk/pull/371
Compiling
> Bumping client base version to 1.1.6

- packages/client/verifiable-credentials/src/presentation/getMetadata.ts
Timeout was in milliseconds and not in seconds
Unit tests
> VC: fix timeout

- packages/client/verifiable-credentials/package.json
- packages/client/verifiable-credentials/src/services/crossmintAPI.ts
- packages/client/verifiable-credentials/src/services/litInterface.test.ts
- packages/client/verifiable-credentials/src/services/litInterface.ts
- packages/client/verifiable-credentials/src/verification/services/signature.ts
Allow the verifiable credentials sdk to be used server side.
Fix verification.
> VC: server side compatibility

- packages/client/wallets/aa/.gitignore
- packages/client/wallets/aa/jest.config.ts
- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/playwright.config.ts
- packages/client/wallets/aa/playwright/tests/demo-todo-app.spec.ts
- packages/client/wallets/aa/playwright/tests/example.spec.ts
- packages/client/wallets/aa/pnpm-lock.yaml
Adding playwright as testing framework for UI testing
Not changing code
> Playwright: include in sdk

- packages/client/wallets/walletconnect/src/components/modals/SessionProposal/SessionProposalViewRouter.tsx
- packages/client/wallets/walletconnect/src/components/modals/SessionRequest/SessionRequestViewRouter.tsx
- packages/client/wallets/walletconnect/src/components/modals/SessionRequest/UnsupportedMethodRequestedModal.tsx
- packages/client/wallets/walletconnect/src/hooks/useWalletConnectRequests.tsx
- packages/client/wallets/walletconnect/src/hooks/useWalletConnectSessions.tsx
- packages/client/wallets/walletconnect/src/i18n/dictionary.ts
- packages/client/wallets/walletconnect/src/utils/wallet/supportedNamespacesSatisfiesMethod.ts
- packages/client/wallets/walletconnect/src/utils/wallet/supportedNamespacesSatisfiesRequiredChains.ts
- packages/client/wallets/walletconnect/src/wallets/WalletConnectEthersWallet.ts
unsupported method modal
locally
> wc: unsupported method modal

- packages/client/wallets/aa/src/blockchain/wallets/ZeroDevEip1193Bridge.ts
[
{
"id": "nft-approval",
"action": "Approve NFT contract",
"description": "Each NFT collection you want to trade requires a one-time approval transaction",
"kind": "transaction",
"items": [
{
"status": "incomplete",
"data": {
"from": "0x05426722092221ddb0cd8a57caf57eea4faefd54",
"to": "0x47cfe3ed0d9ea74e146899e48db2d42be6412ebf",
"data": "0xa22cb4650000000000000000000000001e0049783f008a0085193e00003d00cd54003c710000000000000000000000000000000000000000000000000000000000000001"
},
"orderIndexes": [
0
],
"error": "An unknown RPC error occurred.\n\nRequest Arguments:\n  chain:  Polygon Mumbai (id: 80001)\n  from:   0x05426722092221ddB0CD8A57cAf57eEA4FaEfD54\n  to:     0x47cfe3ed0d9ea74e146899e48db2d42be6412ebf\n  value:  0 MATIC\n  data: …
> SCW-389 Fixed value param on sendtransaction

- packages/client/wallets/aa/src/CrossmintAASDK.ts
- packages/client/wallets/aa/src/api/BaseCrossmintService.ts
- packages/client/wallets/aa/src/blockchain/wallets/BaseWallet.ts
- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
- packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
- packages/client/wallets/aa/src/passkeys/PasskeysSDK.ts
- packages/client/wallets/aa/src/passkeys/services/LitService.ts
- packages/client/wallets/aa/src/services/logging/index.ts
- packages/client/wallets/aa/src/utils/auth.ts
- packages/client/wallets/aa/src/utils/constants.ts
Added Datadog logs on every catch. Also, added a 'service' property to ease the filtering on Datadog 
Filter and search logs on Datadog.
> SCW-382: Set up monitoring approach

- packages/client/base/src/types/events/public/payloads.ts
Needed for https://github.com/Paella-Labs/crossbit-main/pull/11716
It compiles
> Improvement: Include Order info on 'payment:process.started' payload

- packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
- packages/common/base/src/utils/apiKey/validateAPIKey.ts
Solved Latacora's finding on the Security Review. There was a console.error on validateAPIKeySignature that could show a 'signature' value on the stack trace. Removed the error object from the log
Check that no other logs can leak or show sensible information.
> SCW-381: Finding LT-APP24-6

- packages/client/wallets/aa/front/pages/index.tsx
- packages/client/wallets/aa/front/services/walletService.ts
Improvements on the SDK AA Demo to do testing with Playwright
-Create / Get Wallet using Fireblocks
-Input text for Sign Message
-Sign Typed data
-Verify message
Run  `yarn dev` on `packages/client/wallets/aa/front/`
> SCW-391:Improve SDK Demo site

- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
Sync chains with crossmint
The build fails because the AA package doesn't build. But I need this changes release to update the AA package, which I do in https://github.com/Crossmint/crossmint-sdk/pull/399
It's a circular dependency, that's why I need this merged as is.
Manual
> Synced base with crossbit main blockchains

- packages/client/base/package.json
- packages/client/base/src/types/embed/crypto.ts
- packages/client/ui/react-ui/package.json
- packages/client/ui/react-ui/src/components/embed/crypto/CryptoEmbeddedCheckoutIFrame.tsx
Update embedded checkout signer
building the package.
> update embedded checkout signer

- packages/client/starters/vue-ui-starter/src/components/PayWithCC.vue
- packages/client/ui/react-ui/package.json
Update react ui sdk
Built the project
> update react ui

- .github/workflows/main.yml
- package.json
i've already setup actions to create a pr when a changeset is found in main (aka it was created from a pr, and then that pr was merged to main)
this will make it so that when the pr made by the changesets bot is merged, the packages will be released
have to merge to main to test
> cd: update changesets auto publish

- .changeset/itchy-bats-check.md
- packages/client/window/package.json
making the window pkg public + testing changests
ci
> window: testing changesets

- packages/client/base/src/types/hosted/index.ts
- packages/client/base/src/types/hosted/verification.ts
- packages/client/base/src/types/index.ts
- packages/client/ui/react-ui/src/components/hosted/CrossmintVerificationButton.tsx
Design doc: https://docs.google.com/document/d/1iIhjE_CZNA0F4E49mxFN53AADh87jfb2LoRMer_jup0/edit#heading=h.ivay2yrvkmfi
API Design Doc: https://docs.google.com/document/d/1s5EFngSxkcieS3yUPUhm-nIE8bOb1xdfB--sCsmJJ2s/edit
Basically declaring interfaces and placing the base component. Lets discuss if this is the appropriate place for them, and also the interface of the SDK in general.
Build works as expected. Not much to test for now.
> verification-sdk: React component foundations

- packages/client/base/src/services/hosted/crossmintVerificationButtonService.ts
- packages/client/base/src/services/index.ts
- packages/client/base/src/types/hosted/verification.ts
- packages/client/ui/react-ui/src/components/hosted/CrossmintVerificationButton.tsx
- packages/client/ui/react-ui/src/components/hosted/index.ts
- packages/client/window/src/windows/index.ts
- yarn.lock
Sending parameters to hosted page.
Read design doc: https://docs.google.com/document/d/1iIhjE_CZNA0F4E49mxFN53AADh87jfb2LoRMer_jup0/edit#heading=h.ivay2yrvkmfi
Tested locally:
> verification-sdk: sending params to hosted page

- packages/client/wallets/aa/front/abi/ERC1155ABI.json
- packages/client/wallets/aa/front/abi/ERC20ABI.json
- packages/client/wallets/aa/front/abi/ERC721ABI.json
- packages/client/wallets/aa/front/components/CreateWallet.tsx
- packages/client/wallets/aa/front/components/Custodians.tsx
- packages/client/wallets/aa/front/components/LocalStorage.tsx
- packages/client/wallets/aa/front/components/MintAndTransfer.tsx
- packages/client/wallets/aa/front/components/SendTransaction.tsx
- packages/client/wallets/aa/front/components/SignMessages.tsx
- packages/client/wallets/aa/front/pages/index.tsx
- packages/client/wallets/aa/front/services/walletService.ts
Demo page separated in components
Added purge all localstorage data
Added nft transfer test. ERC20, 1155, 721
Execute the demo on the SDK and follow the test plan.
> SCW-395: Improve SDK Demo site v2

- packages/client/ui/react-ui/src/components/hosted/index.ts
Exclude from the bundle for now
CI/CD passing
> verification-sdk: exclude from the bundle for now

- packages/client/wallets/aa/front/components/GetNFTsComponent.tsx
- packages/client/wallets/aa/front/pages/index.tsx
Added a button on the test site for the AA to test the aaWallet.getNFTs() call
Init the demo on the AA SDK package and create an instance of an SCW.
> SCW-422: QA AA -  FetchNFTs button

- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
Add Astar and Apex to enum. This sync with the changes in main
Manual testing
> SCW-390: add Astar and apex to enum (sync with crossbit main)

- packages/client/wallets/aa/src/blockchain/wallets/ZeroDevEip1193Bridge.ts
Added eth_signTypedData_v4 to fix the issue with reservoir
Create AAWallet with ethers signer, getSigner("viem") and then listtoken: 
```
const result = await client.actions.listToken({
listings: [
{
token: `0xad971e94d8c3ef758ac853337034b257552c7caf:1`,
weiPrice: "12200000000000000",
},
],
chainId: 80001,
wallet: walletClient,
expirationTime: 1713040544,
orderbook: "reservoir",  
orderKind: "seaport-v1.5",  
automatedRoyalties: true,
onProgress: (steps: Execute["steps"]) => {
console.log("sell steps", steps);
},
});
console.log("result: ",result)
```
Result:
> SCW-426 Added eth_signTypedData_v4

- packages/common/base/src/types/uiconfig.ts
Adds the hideCardForm param to make only apple pay case
> Embedded v2: hideCardForm

- packages/client/wallets/aa/front/README.md
Including steps to run the tests.
Just modifying the reame.
> README: Improve front readme

- packages/client/base/src/services/useCrossmintEvents.ts
return a cleanup function devs can use to stop listening manually
> listenToMintingEvents: return cleanup function

- packages/client/wallets/aa/src/blockchain/BlockchainNetwoks.test.ts
- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
Changed the polygon-mumbai RPC url to 
["polygon-mumbai", "https://polygon-mumbai-pokt.nodies.app/"].
Create a wallet using "polygon-mumbai" as chain
> SCW-453: change rpc url

- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/types/nft.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
Added hypersonic-testnet to base enum. Updated some classes used in client base later.
Manual Testing
> add hypersonic testnet

- packages/client/verifiable-credentials/package.json
- packages/client/verifiable-credentials/src/services/provider.test.ts
- packages/client/verifiable-credentials/src/services/provider.ts
Updated the rpcs providers
Unit tests and tested manually
> VerifiableCredentials: update RPCs

- packages/client/base/package.json
- packages/client/base/src/utils/ui.ts
Added hypersonic-testnet and a few other chains to the ui component
Manual testing
> Max/update client base to support hypersonic-testnet

- packages/client/ui/react-ui/package.json
Bump react ui to include hypersonic testnet
manual testing
> bump react ui version

- packages/client/base/src/types/embed/index.ts
Adds a debug flag for the event console
https://www.loom.com/share/969ff9e7516448eca28207f650860455?sid=5398d991-f10f-493b-bab3-00b1782f733d
> Debug flag

- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
Added POLYGON-AMOY testnet on base package.
Install the base package and use POLYGON-AMOY as a testnet
> SCW-461: Add polygon-amoy to base package

- packages/client/wallets/walletconnect/package.json
have to release this publicly
n/a
> walletconnect: make pkg public

- .github/workflows/pr-stats-slack.yml
> add pr review slack bot

- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
- packages/client/wallets/aa/src/utils/constants.ts
Added custom PM from Coinbase for base and base-sepolia 
Use the AA SDK using base or base-sepolia
> SCW-469: Coinbase PM

- packages/client/wallets/aa/src/blockchain/BlockchainNetwoks.test.ts
- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
- packages/client/wallets/walletconnect/package.json
- yarn.lock
Polygon Fix: Fix RPC
Created AA locally and mint using it.
> Polygon Fix: Fix RPC

- packages/client/verifiable-credentials/package.json
- packages/client/verifiable-credentials/src/presentation/getCollections.ts
- packages/client/verifiable-credentials/src/presentation/getNfts.ts
- packages/client/verifiable-credentials/src/services/provider.test.ts
- packages/client/verifiable-credentials/src/services/provider.ts
- packages/client/verifiable-credentials/src/verification/services/nftStatus.test.ts
- packages/client/verifiable-credentials/src/verification/services/nftStatus.ts
Switch to use polygon amoy testnet.
Tested manually
> VC: Switch to amoy

- packages/client/wallets/aa/package.json
- packages/client/wallets/walletconnect/package.json
> release: aa

- .github/workflows/pr-stats-slack.yml
> add pr stats slackbot

- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
- packages/client/wallets/aa/src/utils/deferrable.ts
Fixed sendTransaction with the new ZDev version and Viem. 
Send a transaction using the AA SDK.
> SCW-346: Send Transaction fix

- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
- yarn.lock
Implemented SetCustodianForTokens with the new ZeroDev SDK version. 
Call 'setCustodianForTokens' when using the AA SDK.
> SCW346: Set custodian for tokens

- packages/client/wallets/aa/src/blockchain/BlockchainNetwoks.test.ts
- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
Llama RPC caused a `net_version` error. Changing the url resolves it
Created AA locally
> AA: Fix Optimism/Arbitrum RPC

- packages/client/wallets/aa/src/utils/blockchain.ts
- packages/client/wallets/aa/src/utils/index.ts
Add verify message helper
- Sign message with AA && verify same message => true
- Sign Message with AA && verify diff message => false
> AA: Add verify message helper

- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/src/CrossmintAASDK.ts
- packages/client/wallets/aa/src/api/CrossmintWalletService.ts
- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
- packages/client/wallets/aa/src/types/API.ts
- packages/client/wallets/aa/src/types/Config.ts
- yarn.lock
Call crossbit main which returns the appropiate entry point version.
Manual testing
> SCW-346: Entry Point Versioning

- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
AA: Add Zkyoto support and deprecate Zkatana
Created AA Wallet and minted through it
> AA: Add Zkyoto support and deprecate Zkatana

- packages/client/wallets/aa/src/CrossmintAASDK.ts
- packages/client/wallets/aa/src/api/CrossmintWalletService.ts
Accept email or userId when querying for entry point versioning
Manual testing
> SCW-536: Accept userId as entry point versioning

- packages/client/wallets/aa/.gitignore
- packages/client/wallets/aa/package.json
- packages/client/wallets/aa/src/CrossmintAASDK.ts
- packages/client/wallets/aa/src/adapters/reservoir.ts
- packages/client/wallets/aa/src/api/CrossmintWalletService.ts
- packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
- packages/client/wallets/aa/src/types/API.ts
- packages/client/wallets/aa/src/types/Config.ts
- packages/client/wallets/aa/src/utils/blockchain.ts
- packages/client/wallets/aa/src/utils/constants.ts
AA: Add Zkyoto support
Also, improved types and removed/explained the "as ..." used through the EVMAAWallet
Created AA Wallet locally and minted through it.
> AA: Add Zkyoto support 

- packages/client/wallets/aa/src/blockchain/token/Tokens.ts
- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
Leverage typescript for a nice transfer API
Manual
> SCW-538: Transfer function proposal

- packages/client/wallets/aa/src/utils/log.ts
Sorry, forgot to remove some logs while testing
> AA: Remove Logs

- packages/client/base/src/types/errors.ts
Read: https://linear.app/crossmint/issue/PAY-2972/better-error-for-emailinputoptions
Will test in crossbit main
> payment-errors: new handled error payments:recipient.missing

- packages/client/auth-core/src/components/AuthModal.tsx
- packages/client/auth-core/src/contexts/authlogin.tsx
- packages/client/auth-core/src/index.ts
- packages/client/auth-core/src/services/CrossmintService.ts
- packages/client/auth-core/src/utils/constants.ts
- packages/client/auth-core/src/utils/index.ts
- packages/client/auth-core/src/utils/jwt.ts
- packages/client/window/src/EventEmitter.ts
- packages/client/window/src/windows/IFrame.ts
- packages/client/window/src/windows/Popup.ts
(BTW, I pointed it to auth_core because of lerna and working on several sdks at the same time made me difficult to split it properly, will create new PRs if needed )
> [NOT Merge] Window: Add dirty components 

- packages/client/ui/react-ui/package.json
- packages/client/ui/react-ui/src/components/embed/CrossmintPaymentElement.test.tsx
- packages/client/ui/react-ui/src/components/embed/EmbeddedCheckoutIFrame.tsx
- packages/client/ui/react-ui/src/consts/version.ts
this issue presents in multiple live production clients, for example https://www.alexandriabooks.com element is not filling full width
coinbase, not filling full width
**before, css styles with `!important` not being applied at all:**
**now, styles apply correctly**
> embed: fix css

- packages/client/verifiable-credentials/src/crossmintAPI.ts
- packages/client/verifiable-credentials/src/index.ts
- packages/client/verifiable-credentials/src/presentation/getCredential.test.ts
- packages/client/verifiable-credentials/src/presentation/getCredential.ts
- packages/client/verifiable-credentials/src/verifiableCredentialsSKD/configs.ts
- packages/client/verifiable-credentials/src/verifiableCredentialsSKD/presentation/getCollections.ts
- packages/client/verifiable-credentials/src/verifiableCredentialsSKD/types/collection.ts
Minor changes:
- added customizable timeout for ipfs
- return correct VC object from crossmint api
- export procedures
No tests needed
> VC: Added exports

- packages/client/verifiable-credentials/src/services/delegationSignature.ts
- packages/client/verifiable-credentials/src/services/lit.ts
- packages/client/verifiable-credentials/src/verifiableCredentialsSKD/encryption/lit.ts
Retrieve the delegation signature from crossmint when not provided.
GET /api/unstable/credentials/delegationSignature
Tested manually
> VC: retrieve delegation sig

- packages/client/wallets/aa/src/services/logging/ConsoleProvider.ts
Hide console logs locally
Created AA wallet and minted locally (on branch that works with the demo)
> AA: Hide console logs locally

- packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
increase timeout to paymaster
Createad AA and minted locally
> AA: increase timeout on paymaster

- .husky/pre-commit
- package.json
- packages/client/base/package.json
- packages/client/starters/example/package.json
- packages/client/starters/nextjs-starter/package.json
- packages/client/starters/react-ui-starter/package.json
- packages/client/ui/react-ui/package.json
- packages/client/ui/vanilla-ui/package.json
- packages/client/ui/vue-ui/package.json
- packages/client/verifiable-credentials/package.json
- packages/client/wallets/aa/front/package.json
- packages/client/wallets/aa/package.json
- packages/client/wallets/walletconnect/package.json
- packages/client/window/package.json
- packages/common/base/package.json
- yarn.lock
adds husky pre-commit hook
on commit, runs lint-staged on staged code and sorts staged package.jsons
this pr sorts all the package.jsons
no code changes, just housekeeping
> husky pre-commit: lint-staged and sort-package-json

- README.md
- packages/client/ui/react-ui/README.md
- packages/client/ui/vanilla-ui/README.md
> readme: pnpm tweak

- .changeset/config.json
this was causing changesets to sync all versions to be exactly the same, which we dont want
im doing some testing with changesets, to see if we can start using it
> changesets: change linking

- .github/workflows/main.yml
- package.json
tweaking changesets command
this stuff is pretty hard to test... so unfortunately there is a bit of "scary" time rn while i live test this...
> changests: tweak command

- .changeset/itchy-points-poke.md
with the changeset testing i accidentally published a bad package with no dist...
this will fix it now, since i was previously missing the build command in the changeset publish workflow
testing the full changeset flow via this pr
> vc: fix bad publish

- README.md
> readme: new cd process

- packages/client/wallets/aa/src/api/BaseCrossmintService.ts
- packages/client/wallets/aa/src/api/CrossmintWalletService.ts
- packages/client/wallets/aa/src/blockchain/wallets/passkey.ts
Make passkeys server work with external auth header
Manual creation of wallet
> make passkeys server work with external auth guard

- .changeset/sour-shoes-itch.md
- .gitignore
- packages/client/base/package.json
- packages/client/ui/react-ui/package.json
- packages/client/ui/vanilla-ui/package.json
- packages/client/ui/vue-ui/package.json
- pnpm-lock.yaml
this makes development easier and works better with changesets - during publish process, pnpm changes workspace references to the new version being published
gonna test this live, if i fucked it up ill revert...
> feat: use workspace packages

- apps/payments/create-react-app/package.json
- apps/payments/nextjs/package.json
- apps/payments/vue/package.json
- apps/wallets/aa/nextjs/package.json
- packages/client/ui/react-ui/src/consts/version.ts
- packages/client/ui/vanilla-ui/src/consts/version.ts
- pnpm-lock.yaml
i think this should fix it, but a similar thing might happen again in the future
ci + main ci
> fix: more workspace pkgs

- packages/client/wallets/smart-wallet/src/blockchain/wallets/service.ts
- packages/client/wallets/smart-wallet/src/index.ts
- packages/client/wallets/smart-wallet/src/types/Error.ts
- packages/client/wallets/smart-wallet/src/utils/signer.ts
Had a chat w/ Claude about how we should cleanup and format our SDK errors.
TS Compiling and CI passing.
> Smart Wallet: Custom Error Cleanup

- packages/common/base/src/apiClient/ApiClient.ts
- packages/common/base/src/apiClient/CrossmintApiClient.ts
- packages/common/base/src/apiClient/CrossmintClientSideApiClient.ts
- packages/common/base/src/apiClient/CrossmintServerSideApiClient.ts
- packages/common/base/src/apiClient/index.ts
- packages/common/base/src/apiKey/validateAPIKeyPrefix.ts
- packages/common/base/src/index.ts
this is a common api client, which _should_ be used for basically all client + server side crossmint api interactions
first one being with embedded checkout v3
> feat: api client

- packages/client/ui/react-ui/src/hooks/index.ts
- packages/client/ui/react-ui/src/hooks/useCrossmint.tsx
- packages/client/ui/react-ui/src/index.ts
top level react provider exposing apiClient
tested with embed v3
> feat: react sdk provider

- packages/client/wallets/smart-wallet/src/SmartWalletSDK.ts
- packages/client/wallets/smart-wallet/src/blockchain/wallets/passkey.ts
- packages/client/wallets/smart-wallet/src/types/Config.ts
Make passkey names optional, default to JWT identifier (usually sub)
Manual testing
> WAL-2455: make passkeys name optional

- apps/wallets/smart-wallet/react/package.json
- apps/wallets/smart-wallet/react/src/app/utils/createAAWallet/createPasskeyWallet.ts
- apps/wallets/smart-wallet/react/src/app/utils/createAAWallet/createViemWallet.ts
- apps/wallets/smart-wallet/react/src/app/utils/createAAWallet/createW3AAAWallet.ts
- pnpm-lock.yaml
This PR:
- updates to the latest smart wallet SDK release
- installs and uses the new web3auth adapter.
Go through both the passkey and w3a flow, creating a new wallet, and minting for each one.
> Smart Wallets: Update Demo With Latest SDK Changes

- packages/client/wallets/smart-wallet/src/api/CrossmintWalletService.ts
Check https://github.com/Paella-Labs/crossbit-main/pull/14088 for details.
This PR removes newly redundant 404 handling when fetching signers.
Locally created a new passkey wallet and minted an NFT.
> Smart Wallets: Drop 404 Handling When Fetching Signers

- packages/client/base/package.json
- packages/client/base/src/types/embed/index.ts
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
- packages/client/base/src/types/embed/v3/events/EmbeddedCheckoutV3IFrameEmitter.ts
- packages/client/base/src/types/embed/v3/events/incoming.ts
- packages/client/base/src/types/embed/v3/events/index.ts
- packages/client/base/src/types/embed/v3/events/outgoing.ts
- packages/client/base/src/types/embed/v3/index.ts
- packages/client/ui/react-ui/package.json
- packages/client/ui/react-ui/src/components/embed/v3/CrossmintEmbeddedCheckoutV3.tsx
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
- packages/client/ui/react-ui/src/components/embed/v3/index.tsx
- packages/client/ui/react-ui/src/components/index.ts
- packages/client/window/package.json
- pnpm-lock.yaml
starting react component, tweaked a bit in https://github.com/Crossmint/crossmint-sdk/pull/588
tested locally nextjs starter
> embed v3: prop types + starting react comp

- apps/payments/nextjs/pages/embedded-checkout/v3.tsx
- packages/client/base/package.json
- packages/client/base/src/services/embed/index.ts
- packages/client/base/src/services/embed/v3/crossmintEmbeddedCheckoutV3Service.ts
- packages/client/base/src/services/embed/v3/index.ts
- packages/client/base/src/services/hosted/index.ts
- packages/client/base/src/services/index.ts
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
- packages/client/window/src/windows/IFrame.ts
- packages/common/base/src/apiClient/CrossmintApiClient.ts
- pnpm-lock.yaml
common service
local with demo app
iframe has correct params
> embed v3: common service

- .changeset/violet-dogs-live.md
- apps/payments/create-react-app/package.json
- apps/payments/nextjs/package.json
- packages/client/base/package.json
- packages/client/ui/react-ui/package.json
- packages/client/wallets/walletconnect/package.json
- pnpm-lock.yaml
hoping to fix the rpc-websocket bug
using the lib no longer has the missing rpc-websocket error
> bump: @solana/web3.js

- apps/payments/nextjs/pages/embedded-checkout/v3.tsx
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
appearance types
local with crossmint-main + sdk test app
> embed v3: appearance types

- packages/common/base/src/apiClient/ApiClient.ts
- packages/common/base/src/apiClient/CrossmintApiClient.ts
- packages/common/base/src/apiClient/CrossmintClientSideApiClient.ts
- packages/common/base/src/apiClient/CrossmintServerSideApiClient.ts
- packages/common/base/src/apiClient/index.ts
- packages/common/base/src/apiKey/validateAPIKeyPrefix.ts
- packages/common/base/src/index.ts
code already approved in https://github.com/Crossmint/crossmint-sdk/pull/572 + tweaks
been testing with embed v3
> common apiclient: copy of #572 + tweaks

- apps/wallets/smart-wallet/react/src/app/utils/mintApi.ts
- packages/client/wallets/smart-wallet/src/api/APIErrorService.ts
- packages/client/wallets/smart-wallet/src/error/index.ts
- packages/client/wallets/smart-wallet/src/index.ts
Handle the 402 exception we throw when out of credits. Looking for feedback on the error and message since it isn't from the spec
Mocked crossbit-main to throw this error and ensured the SDK handled it properly
> Throw good error when out of credits

- packages/client/wallets/smart-wallet/src/api/APIErrorService.ts
- packages/client/wallets/smart-wallet/src/error/index.ts
- packages/client/wallets/smart-wallet/src/index.ts
Resolves https://linear.app/crossmint/issue/WAL-2458/throw-good-error-trying-to-create-a-second-wallet-for-a-user
Requires https://github.com/Paella-Labs/crossbit-main/pull/14131
Doesn't add any new logic, just new data
> Throw good error trying to create a second wallet for a user

- .changeset/quick-carrots-smile.md
- packages/client/verifiable-credentials/src/presentation/getCredential.test.ts
- packages/client/verifiable-credentials/src/presentation/getCredential.ts
- packages/client/verifiable-credentials/src/services/delegationSignature.ts
- packages/client/verifiable-credentials/src/services/walletAuth.ts
Moved to the `v1-alpha1` api version.
Manual flow tested
> VC: api update

- .changeset/five-dragons-poke.md
Bump version to release API client classes
Nothing changed to test
> version bump: @crossmint/common-sdk-base

- apps/payments/vue/package.json
- apps/wallets/smart-wallet/nextjs/package.json
- packages/client/ui/react-ui/src/consts/version.ts
- packages/client/ui/vanilla-ui/src/consts/version.ts
- packages/client/verifiable-credentials/package.json
- packages/client/wallets/aa/package.json
- pnpm-lock.yaml
should fix release cd
this pr should go green
> pkgs: use more workspace:*

- .changeset/hungry-lions-boil.md
- packages/client/auth-core/package.json
Auth: Make it public
Auth: Make it public
> Auth: Make it public

- .changeset/angry-maps-learn.md
- packages/client/window/src/utils/popupStrategy.ts
- packages/client/window/src/windows/Popup.ts
Window: Add Cross-origin param
Auth flow tested locally
> Window: Add Cross origin param

- crossmint-sdk.code-workspace
QOL improvement
Workspace operates properly when using VSCode
> Smart Wallets: Add SDK To VSCode Workspaces File

- .changeset/curly-yaks-agree.md
Should have added this in https://github.com/Crossmint/crossmint-sdk/pull/627
N/A
> Smart Wallets: Change Set

- packages/client/wallets/smart-wallet/src/blockchain/token/index.ts
Removes redundant incorrect export
TS compiles
> Smart Wallet: Fix Broken Export

- packages/client/wallets/smart-wallet/src/SmartWalletSDK.ts
- packages/client/wallets/smart-wallet/src/api/CrossmintWalletService.ts
- packages/client/wallets/smart-wallet/src/blockchain/wallets/paymaster.ts
- packages/client/wallets/smart-wallet/src/blockchain/wallets/service.ts
- packages/client/wallets/smart-wallet/src/utils/api.ts
Adds code to use our Paymaster API, as well as an external SDK method (can discuss in the review if we want to keep this)
Need to land https://github.com/Paella-Labs/crossbit-main/pull/14258 before merging
Tested locally e2e with crossbit-main changes
> AA: Crossmint Paymaster API

- packages/common/base/src/apiClient/ApiClient.ts
- packages/common/base/src/apiClient/CrossmintApiClient.ts
> api client: fix dynamic auth headers

- packages/client/verifiable-credentials/src/verifiableCredentialsSDK/verification/signature.test.ts
- packages/client/verifiable-credentials/src/verifiableCredentialsSDK/verification/signature.ts
f the issuer in a VC got tampered and an invalid address was put the verification util would error out instead of returning invalid credential.
Unit test added
> VC: fix verification invalid issuer

- packages/client/auth-core/src/components/AuthModal.tsx
- packages/client/auth-core/src/contexts/authlogin.tsx
Auth Core: Change approach on 3P JWT
Executed the whole auth flow locally
> Auth Core: Change approach on 3P JWT

- packages/client/wallets/smart-wallet/src/api/APIErrorService.ts
- packages/client/wallets/smart-wallet/src/error/index.ts
- packages/client/wallets/smart-wallet/src/index.ts
Iterating on the wording here based on feedback from jon setting up a project on the via console for the first time and using the smart wallet SDK.
Existing CI should be good here!
> Smart Wallet: Improve Project Configuration Error

- .changeset/fair-suns-sin.md
- packages/client/verifiable-credentials/src/presentation/getNfts.ts
Use the `credentials nft only` endpoint to speed up credentials retrieval.
Unit tests
> VC: Use vc only enpoint

- .changeset/tiny-parrots-approve.md
minor patch, bringing this up to date in anticipation of auth release.
N/A
> Smart Wallets: Patch 0.1.3

- .changeset/moody-ways-clean.md
> Added Changeset

- .changeset/grumpy-kangaroos-teach.md
Turns out these need to be released as well!
N/A
> Base Packages Change Set

- apps/wallets/smart-wallet/next/src/app/page.tsx
- apps/wallets/smart-wallet/next/src/components/header.tsx
Adjusted padding top
App still functions the same
> Next.js demo: padding top adjustment

- packages/client/ui/react-ui/src/consts/version.ts
- packages/client/ui/vanilla-ui/src/consts/version.ts
> Auto versioning update

- .changeset/perfect-needles-smile.md
- packages/common/base/src/apiKey/validateAPIKeyPrefix.ts
Base: Make getEnvironmentForKey public
Tested Locally
> Base: Make getEnvironmentForKey public

- packages/client/wallets/smart-wallet/src/blockchain/chains.ts
- packages/client/wallets/smart-wallet/src/blockchain/rpc.ts
- packages/client/wallets/smart-wallet/src/blockchain/wallets/service.ts
this is recommended by ZeroDev
We got blocked for some simple RPC calls that led to wallets failing to create
This is ZeroDev's recommendation
Haven't yet
> use Alchemy RPC for publicClient

- .changeset/strange-adults-flow.md
- packages/client/wallets/smart-wallet/src/api/CrossmintWalletService.ts
We need e2e tests urgently!
This PR fixes a regression introduced [here](https://github.com/Crossmint/crossmint-sdk/pull/676)
Created a new passkey wallet and minted.
> Smart Wallet: Fix Passkey Registration Regression

- .changeset/late-buttons-relate.md
- packages/client/window/src/windows/Popup.ts
Window: Fix issue about never returning on popup init
Tested through the auth SDK flow
> Window: Fix issue about never returning on popup init

- .changeset/wise-cooks-hang.md
> Auth Core: Patch release

- apps/wallets/smart-wallet/next/package.json
- packages/client/ui/react-ui/src/consts/version.ts
- pnpm-lock.yaml
This PR bumps the `@crossmint/client-sdk-react-ui` package the smart wallets + auth demo used.
N/A
> Smart Wallet + Auth: Update Package Used in Demo

- apps/wallets/smart-wallet/next/package.json
- pnpm-lock.yaml
This PR updates the Smart Wallet + Auth Demo to use the workspace package for `@crossmint/client-sdk-react-ui` so that SDK changes & corresponding demo updates can be made within the same PR.
To accommodate this, I've updated Vercel to only build on the `smart-wallet-auth-demo-prod` branch, which will use the versioned package.
N/A
> Use Workspace For Smart Wallet Demo

- .changeset/spicy-countries-sort.md
This PR adds a changeset for the `CrossmintWalletProvider` and accompanying SDK changes and recent speed improvements.
N/A
> Smart Wallets: Add Changeset

- .changeset/gorgeous-bottles-live.md
> Changeset: Auth Core

- .changeset/healthy-fans-breathe.md
This PR adds a changeset for the new `executeContract` function
N/A
> Changeset: `executeContract`

- .changeset/poor-dodos-build.md
> Changeset: Base SDK Update

- pull_request_template.md
We need this! I've accidentally released broken packages because I missed a changeset more than once.
N/A
> QOL: Add to PR Template

- .changeset/rare-pigs-drop.md
- packages/client/verifiable-credentials/src/presentation/getNfts.ts
- packages/client/verifiable-credentials/src/verifiableCredentialsSDK/types/nft.ts
Returning also the nfts metadata when returning credentials nfts
> VC: nft metadata

- .changeset/khaki-balloons-complain.md
- packages/client/auth-core/src/components/ActionModal.tsx
Updated css style to blur background 
na - only touches style 
- @crossmint/client-sdk-auth-core
> Blur Auth Modal Background

- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.test.tsx
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
Expose `status` prop in `useAuth` hook to enable better loading UX in applications. This change allows developers to create more responsive interfaces by providing granular control over authentication states. Also added test case for new prop.
Ensure demo still works as usual and all loading UX is suffice.
**@crossmint/client-sdk-react-ui** 
- added prop 'status' to useAuth hook
- updated test case
> React-ui: Exposed status prop in useAuth

- .changeset/curvy-apples-refuse.md
- packages/client/ui/react-ui/src/components/auth/AuthModal.tsx
Note: this is Part 1/2 PR's for responsive modal styles. This adds necessary responsive styles to the react-ui auth modal.
App works as expected, modal is now responsive!
**@crossmint/client-sdk-react-ui**
> Auth modal: Responsive modal styles

- .changeset/violet-steaks-learn.md
We missed a few of these, adding them before doing a release.
n/a
> Changeset: Sept 10, 2024

- .github/workflows/main.yml
follow up to https://github.com/Crossmint/crossmint-sdk/pull/729 for `main.ci` which has been failing.
After this is merged `main.ci` should work.
none
> CI: Add env var to `main.ci`

- .changeset/happy-swans-sell.md
- .changeset/wise-buses-sin.md
- packages/client/ui/react-ui/src/index.ts
- packages/client/wallets/smart-wallet/src/index.ts
We forgot about these.
N/A
Patch to `@crossmint/client-sdk-smart-wallet` and `@crossmint/client-sdk-react-ui`
> Smart Wallets: Export `executeContract` Errors

- .changeset/nine-zebras-learn.md
- packages/client/ui/react-ui/README.md
Link to smart wallet quickstart from `@crossmint/client-sdk-react-ui`.
n/a
Update to `@crossmint/client-sdk-react-ui`
> React UI: Update Readme

- apps/wallets/smart-wallet/next/src/app/page.tsx
- apps/wallets/smart-wallet/next/src/components/fireworks.tsx
Improves the conditions in which the sign in button is shown to make sure it doesn't disappear after minting an nft and then signing out
Sign In => Mint an NFT => Sign Out and the sign in button should appear
None
> Fixes how sign in button is loaded in aa demo to avoid it disappearing

- .changeset/wicked-melons-matter.md
- packages/client/verifiable-credentials/package.json
- pnpm-lock.yaml
> VC: fix dep

- .changeset/selfish-cows-fix.md
- packages/client/ui/react-ui/package.json
- packages/client/ui/react-ui/src/components/auth/AuthModal.tsx
- packages/client/ui/react-ui/src/consts/version.ts
- packages/client/ui/react-ui/src/index.ts
- packages/client/ui/react-ui/src/lib/utils.ts
- packages/client/ui/react-ui/src/twind.config.ts
- packages/client/ui/react-ui/src/utils/classNames.ts
- packages/client/ui/react-ui/tsconfig.json
- pnpm-lock.yaml
Twind is a small, fast, and feature-rich CSS(tailwind)-in-JS library. It allows us to use Tailwind classes in our react-ui package.
tldr; It's a runtime CSS-in-JS solution with Tailwind syntax using a lightweight compiler 
https://twind.style/
I've added a `cn` utility funciton for ease of class merging, and replaced our auth modal iframe styles from inline to tailwind classes for the sake of testing it out to make sure it works. 
tldr; I've tested build mode, dev mode and the auth flow with default styles and custom styles and it all works as expected. I've also configured twind to use the default tailwind preset `presetTailwind` so that we get ootb tailwind presets.
> @crossmint/client-sdk-react-ui: Twind (Tailwind-in-js)

- .changeset/witty-cherries-battle.md
- packages/client/ui/react-ui/src/index.ts
This PR exposes a couple new types from `@crossmint/client-sdk-react-ui` that I'm realizing are useful after reviewing some of our pending integration docs.
TS compiles, build passes
Patch `@crossmint/client-sdk-react-ui`
> Smart Wallets: Expose Signer Types From React UI Package.

- packages/client/ui/react-ui/package.json
- packages/client/ui/react-ui/src/consts/version.ts
- packages/client/ui/vanilla-ui/package.json
- packages/client/ui/vanilla-ui/src/consts/version.ts
You know those annoying files that get auto generated and appear in your version control? well this PR allows you to never have to worry about those again XD 
Ensure this doesn't break anything.
> Remove auto generating version scripts

- .changeset/lemon-donuts-search.md
- packages/client/wallets/smart-wallet/src/SmartWalletSDK.ts
- packages/client/wallets/smart-wallet/src/utils/constants.ts
This PR pulls the package version from `package.json`
Sanity checked the Auth + Smart wallet demo, confirming the sdk version is as expected with logs.
patch `@crossmint/client-sdk-smart-wallet`
> Smart Wallets: Accurate SDK Version

- apps/wallets/smart-wallet/next/README.md
- package.json
Updated smart wallets next.js demo readme auth provider code example as well as release instructions for updating the package.
This pr also fixes the pre-commit hook for Biome to not format md | mdx files. 
readme is looking better than ever 👌 
> Update smart wallets demo readme (Resolves WAL-2858)

- apps/wallets/smart-wallet/next/package.json
- pnpm-lock.yaml
New Smarter Wallets release with latest changes in `main` and updating `@crossmint/client-sdk-react-ui` to `v1.4.0` with new Refresk Token
Not needed
None
> Updates @crossmint/client-sdk-react-ui to v1.4.0

- apps/payments/create-react-app/package.json
- apps/wallets/smart-wallet/next/package.json
- apps/wallets/smart-wallet/react/package.json
- packages/client/auth-core/package.json
- packages/client/ui/react-ui/package.json
- packages/client/wallets/smart-wallet/package.json
- pnpm-lock.yaml
Smarter Wallets demo to version 1.5.0 !
na
na
> Smart Wallet auth demo: version bump

- .changeset/grumpy-parents-care.md
- packages/client/ui/react-ui/src/components/auth/AuthModal.tsx
Leftover from #797 
Builds and type checks properly
@crossmint/client-sdk-react-ui: patch
> Fixes type import

- apps/payments/create-react-app/package.json
- package.json
- packages/client/base/package.json
- packages/client/base/tsup.config.ts
- packages/client/ui/react-ui/package.json
- packages/client/ui/react-ui/tsup.config.ts
- packages/client/verifiable-credentials/package.json
- packages/client/verifiable-credentials/tsup.config.ts
- packages/client/wallets/smart-wallet/package.json
- packages/client/wallets/smart-wallet/tsup.config.ts
- packages/client/window/package.json
- packages/client/window/tsup.config.ts
- packages/common/base/package.json
- packages/common/base/tsup.config.ts
- tsup.config.base.ts
making most of the packages tree shakable
u can see the bundle sizes of our apps has been decreased (new is on the right)
tested payments demo nextjs app
> infra: make most pkgs tree shakable

- .github/workflows/main.yml
- package.json
- packages/client/auth-core/package.json
- packages/client/auth/package.json
- packages/common/auth/package.json
- packages/server/package.json
hopefully this fixes lint after release
local, seems to correctly fix the newly updated package.jsons
> changeset: lint fix after version

- .changeset/olive-readers-brush.md
- packages/client/auth-core/src/services/CrossmintAuthService.ts
- packages/client/auth-core/src/utils/constants.ts
Auth: Refactor getUser from client to use versioned route
Execute it locally
"@crossmint/client-sdk-auth-core": minor
> Auth: Refactor getUser from client to use versioned route

- apps/payments/nextjs/pages/embedded-checkout/v3.tsx
- packages/client/ui/react-ui/src/components/embed/v3/CrossmintEmbeddedCheckoutV3.tsx
Rename to alpha
Relying on build
> v3: Rename component for v0 release

- packages/client/base/src/types/CryptoCurrency.ts
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
- packages/client/base/src/types/index.ts
sync some types
preparing for releas
types already used in crossmint-main
> embed: update types

- packages/client/ui/react-ui/src/components/dynamic-xyz/DynamicContextProviderWrapper.tsx
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
- packages/client/ui/react-ui/src/components/embed/v3/crypto/CryptoWalletConnectionHandler.tsx
change dynamic env based on api key env
changes env correctly
> embed: dynamicxyz env

- README.md
> readme: remove beta

- apps/wallets/smart-wallet/next/src/app/_lib/providers.tsx
Add farcaster login method to smart wallet auth demo
regular flow works
na
> Auth: add Farcaster auth method to demo

- .changeset/neat-colts-occur.md
- .changeset/shaggy-impalas-matter.md
na
na
@crossmint/common-sdk-auth
> Changesets: Removal of auth iframe, updated common auth sdk

- .changeset/quick-pumpkins-burn.md
- packages/client/ui/react-ui/src/components/dynamic-xyz/DynamicContextProviderWrapper.tsx
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
- packages/client/ui/react-ui/src/components/embed/v3/crypto/CryptoWalletConnectionHandler.tsx
for some reason [this original pr](https://github.com/Crossmint/crossmint-sdk/pull/825/commits) didnt apply
already approved
> embed: dynamic.xyz stuff

- .changeset/fast-nails-stare.md
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
add receipt email to payment
not much to test
> embed: add receipt email props

- .changeset/silent-countries-run.md
- packages/client/base/src/index.ts
- packages/client/base/src/lib/hosted-checkout/Order.ts
- packages/client/base/src/lib/hosted-checkout/index.ts
- packages/client/base/src/lib/index.ts
- packages/client/ui/react-ui/package.json
- packages/client/ui/react-ui/src/hooks/useCrossmintCheckout.tsx
use real order type
there is really no easy way to share this type which is in crossmint-main, so just copying it
hook has the correct types now
> embed: use real order type

- .changeset/weak-toes-try.md
- apps/payments/nextjs/components/embed-v3/EmbeddedCheckoutV3ClientProviders.tsx
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
- packages/client/ui/react-ui/src/hooks/useCrossmintCheckout.tsx
force client key
errors when using server key
> embed: force client key

- apps/payments/nextjs/pages/hosted-checkout/v3.tsx
- packages/client/base/src/services/hosted/v3/index.ts
- packages/client/base/src/services/hosted/v3/styles/crossmintHostedCheckoutV3StylesService.ts
- packages/client/base/src/types/hosted/v3/CrossmintHostedCheckoutV3Props.ts
- packages/client/base/src/utils/i18n/dictionaries/deDE.ts
- packages/client/base/src/utils/i18n/dictionaries/enUS.ts
- packages/client/base/src/utils/i18n/dictionaries/esES.ts
- packages/client/base/src/utils/i18n/dictionaries/frFR.ts
- packages/client/base/src/utils/i18n/dictionaries/itIT.ts
- packages/client/base/src/utils/i18n/dictionaries/jaJp.ts
- packages/client/base/src/utils/i18n/dictionaries/koKR.ts
- packages/client/base/src/utils/i18n/dictionaries/ptPT.ts
- packages/client/base/src/utils/i18n/dictionaries/ruRU.ts
- packages/client/base/src/utils/i18n/dictionaries/thTH.ts
- packages/client/base/src/utils/i18n/dictionaries/trTR.ts
- packages/client/base/src/utils/i18n/dictionaries/ukUA.ts
- packages/client/base/src/utils/i18n/dictionaries/viVN.ts
- packages/client/base/src/utils/i18n/dictionaries/zhCN.ts
- packages/client/base/src/utils/i18n/dictionaries/zhTW.ts
- packages/client/base/src/utils/i18n/index.ts
- packages/client/ui/react-ui/src/components/common/CrossmintLogoV2/CrossmintLogoV2.tsx
- packages/client/ui/react-ui/src/components/hosted/v3/CrossmintHostedCheckoutV3.tsx
looking 🔥🔥
setup a local test page
> hosted v3: button styles + text

- apps/payments/nextjs/pages/hosted-checkout/v3.tsx
- packages/client/base/src/services/hosted/v3/index.ts
- packages/client/base/src/services/hosted/v3/styles/crossmintHostedCheckoutV3StylesService.ts
- packages/client/base/src/types/hosted/v3/CrossmintHostedCheckoutV3Props.ts
- packages/client/base/src/utils/i18n/dictionaries/deDE.ts
- packages/client/base/src/utils/i18n/dictionaries/enUS.ts
- packages/client/base/src/utils/i18n/dictionaries/esES.ts
- packages/client/base/src/utils/i18n/dictionaries/frFR.ts
- packages/client/base/src/utils/i18n/dictionaries/itIT.ts
- packages/client/base/src/utils/i18n/dictionaries/jaJp.ts
- packages/client/base/src/utils/i18n/dictionaries/koKR.ts
- packages/client/base/src/utils/i18n/dictionaries/ptPT.ts
- packages/client/base/src/utils/i18n/dictionaries/ruRU.ts
- packages/client/base/src/utils/i18n/dictionaries/thTH.ts
- packages/client/base/src/utils/i18n/dictionaries/trTR.ts
- packages/client/base/src/utils/i18n/dictionaries/ukUA.ts
- packages/client/base/src/utils/i18n/dictionaries/viVN.ts
- packages/client/base/src/utils/i18n/dictionaries/zhCN.ts
- packages/client/base/src/utils/i18n/dictionaries/zhTW.ts
- packages/client/base/src/utils/i18n/index.ts
- packages/client/ui/react-ui/src/components/common/CrossmintLogoV2/CrossmintLogoV2.tsx
- packages/client/ui/react-ui/src/components/common/CrossmintLogoV2/consts.ts
- packages/client/ui/react-ui/src/components/common/CrossmintLogoV2/schemas.ts
- packages/client/ui/react-ui/src/components/hosted/v3/CrossmintHostedCheckoutV3.tsx
adding this component
its the same exact component we have in crossmint-main
> hosted: add crossmint logo

- .changeset/violet-bugs-burn.md
- apps/payments/nextjs/next.config.js
- apps/payments/nextjs/package.json
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
- packages/client/ui/react-ui/src/components/embed/v3/crypto/utils/handleSendTransaction.ts
- pnpm-lock.yaml
reduces bundle size pretty heavily
before
after
> embed v3: dynamic wallet conn import

- .changeset/modern-brooms-cross.md
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
- packages/client/ui/react-ui/src/components/embed/v3/crypto/CryptoWalletConnectionHandler.tsx
fix requiring double clicking
did a ton of testing to get this to work...
> embed: fix dynamic bugs

- apps/payments/nextjs/pages/hosted-checkout/v3.tsx
- packages/client/base/src/services/hosted/v3/crossmintHostedCheckoutOverlayService.ts
- packages/client/base/src/types/hosted/v3/CrossmintHostedCheckoutV3Props.ts
small tweak
local with crossmint-main
> hosted v3: tweaks

- packages/client/base/src/services/hosted/v3/crossmintHostedCheckoutOverlayService.ts
- packages/client/base/src/services/hosted/v3/crossmintHostedCheckoutV3Service.ts
- packages/client/window/src/windows/NewTab.ts
- packages/client/window/src/windows/index.ts
new tab window client
local, tested setting pay button to open in new tab
> window: new tab client

- .changeset/nasty-fireants-pay.md
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
sdk side of https://github.com/Paella-Labs/crossbit-main/pull/16049/files
local with crossmint-main
> embed: init existing order Id

- .changeset/angry-feet-film.md
- packages/client/ui/react-ui/package.json
- pnpm-lock.yaml
this is just a warning, not critical - but lets fix it anyways
https://crossmint.slack.com/archives/C05KCC0H61J/p1731600910418269
no longer get a pino-pretty missing warning
> chore: fix pino-pretty warning

- .changeset/rare-falcons-agree.md
- packages/client/base/src/types/hosted/v3/CrossmintHostedCheckoutV3Props.ts
- packages/client/ui/react-ui/src/components/hosted/v3/CrossmintHostedCheckoutV3.tsx
self explanatory
self explanatory
> hosted: fix dumb typo

- .changeset/eighty-points-sing.md
- apps/payments/nextjs/components/embed-v3/EmbeddedCheckoutV3Content.tsx
- packages/client/ui/react-ui/src/components/embed/v3/CrossmintEmbeddedCheckoutV3.tsx
Remove alpha from component. We are ready.
> embedded-v3: removing alpha from component

- .changeset/lovely-guests-sell.md
- .changeset/stupid-humans-enjoy.md
- apps/wallets/smart-wallet/next/src/app/_lib/providers.tsx
- packages/client/ui/react-ui/src/components/auth/AuthForm.tsx
- packages/client/ui/react-ui/src/components/auth/methods/twitter/TwitterSignIn.tsx
- packages/client/ui/react-ui/src/components/auth/methods/x/XSignIn.tsx
- packages/client/ui/react-ui/src/icons/twitter.tsx
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.test.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.tsx
- packages/common/auth/src/types/authmaterial.ts
Add twitter auth to our auth adk
tested end to end flow, twitter users are now created and used in our system via stytch! 
@crossmint/common-sdk-auth
> Auth: Twitter

- .changeset/rich-papayas-jam.md
- .changeset/tough-snails-drop.md
- packages/client/auth/src/CrossmintAuthClient.ts
- packages/client/ui/react-ui/src/components/auth/AuthForm.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.test.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.tsx
Update and improve verbiage for telling user's to whitelist the api key being used. 
Tests pass, ci pass, verbiage needs to pass UX 
@crossmint/client-sdk-auth
> Auth: Verbiage for whitelisting api key

- .changeset/lazy-walls-think.md
- README.md
- packages/client/ui/react-ui/README.md
Our readme is extremely outdated. This contains changes to our primary SDK readme.md as well as our `@crossmint/client-sdk-react-ui` readme
Ensures readme reads correctly and no errors to links 
> Improved SDK Readme.md

- .changeset/clever-camels-perform.md
- packages/common/auth/src/types/user.ts
> auth: twitter user type

- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
Adding a new supported chain to the SDK!
Jut the building and UTs passing
> Add Story testnet

- .changeset/nasty-ducks-unite.md
- apps/payments/nextjs/components/embed-v3/EmbeddedCheckoutV3Content.tsx
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
For memes, as discussed in API Doc
Tested. Works, the param is set correctly
> embedded-props: add execution parameters

- .changeset/healthy-bees-do.md
- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
Adding Chiliz to enable pay with crypto
Tested locally.
> chain: add Chiliz

- apps/wallets/smart-wallet/next/src/app/page.tsx
- apps/wallets/smart-wallet/next/src/app/wallet/page.tsx
- apps/wallets/smart-wallet/next/src/components/secured-by-crossmint.tsx
This PR makes changes to core verbiage on the home page and wallets page. 
changes include: 
- home heading, body text, nft card text
- replaced "powered by" with "secured by" 
- wallet page heading
Tested and works 
na
> Wallet Demo: Updated verbiage

- .changeset/rotten-avocados-develop.md
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
> auth: initializing status

- .changeset/curvy-horses-refuse.md
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
This was making it so we always had to declare both. This fixes.
Tested in my machine. This works.
> embedded: fixing embedded checkout types for line items

- .changeset/pink-dots-invite.md
- packages/client/auth/src/CrossmintAuthClient.ts
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
- packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.test.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.tsx
Fix the callback and marked prop as EXPERIMENTAL
tested
> Fix: onSuccessLogin callback

- .changeset/warm-trains-sit.md
- packages/client/ui/react-ui/src/components/auth/methods/email/EmailOTPInput.tsx
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.test.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.tsx
Last release pckg broke the onLoginSuccess callback. 
expose prefetchOAuthUrls prop  
tested
> Fix: onSuccessLogin callback add prop

- .changeset/wise-dragons-laugh.md
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
add physical address + product locator
local with xmint main
> checkout: update types for product locator

- .changeset/old-jars-own.md
- packages/client/ui/react-ui/src/components/embed/v3/crypto/CryptoWalletConnectionHandler.tsx
> embed: crypto error message

- .changeset/flat-rice-argue.md
- packages/wallets/src/evm/index.ts
- packages/wallets/src/index.ts
- packages/wallets/src/solana/index.ts
Exposing a few necessary types for our react package. 
Exported types work as expected
> Wallets SDK: expose necessary types

- .changeset/chatty-tips-fail.md
- packages/wallets/src/evm/utils.ts
- packages/wallets/src/evm/wallet.ts
- packages/wallets/src/sdk.ts
- packages/wallets/src/services/types.ts
- packages/wallets/src/services/wallet-factory.ts
- packages/wallets/src/solana/services/transactions-service.ts
- packages/wallets/src/solana/wallet.ts
- packages/wallets/src/utils/options.ts
Essential improvements to the Wallets SDK to unlock React and RN work:
* Add `getWallet` function to get existing (server) wallets
* Add (optional) `options` param to define wallet action callbacks
* Add (optional) `experimental_sign` to the passkey signer config to override the message signing
* CI pass
* It should be possible to provide a custom signing function when using passkeys (useful for RN)
* It should be possible to define callbacks based on wallet/tx creation (useful for React SDK)
```
"@crossmint/wallets-sdk": patch
```
> Wallets SDK improvements

- .changeset/curly-mangos-cross.md
- packages/client/ui/react-ui/README.md
Update the readme to reflect latest sdk changes!
ensure readme makes sense and is accurate.
> React SDK: Update readme

- packages/wallets/README.md
Fixes Solana examples in the Wallets SDK readme.
- CI
- Examples are valid code
N/A
> Wallets SDK: update Solana examples

- packages/client/base/src/types/CryptoCurrency.ts
> embed: add pirate

- .changeset/hip-fireants-check.md
- packages/client/ui/react-ui/src/components/dynamic-xyz/DynamicContextProviderWrapper.tsx
- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
Adding Boss
Boss working:
Other chains as well:
> boss: add pay with boss

- .changeset/famous-owls-swim.md
- packages/client/auth/README.md
- packages/client/auth/src/CrossmintAuthClient.test.ts
- packages/client/auth/src/CrossmintAuthClient.ts
- packages/client/auth/src/utils/index.ts
- packages/client/auth/src/utils/storage.test.ts
- packages/client/auth/src/utils/storage.ts
We need non-cookie options for other environments such as react native
Tested with expo app and with smarter wallet
@client-auth: minor
> Auth: Adds support for custom storage solutions in auth sdk

- .changeset/few-mice-care.md
- apps/wallets/smart-wallet/expo/app/index.tsx
- apps/wallets/smart-wallet/next/src/app/wallet/page.tsx
- apps/wallets/smart-wallet/next/src/components/header.tsx
- apps/wallets/smart-wallet/next/src/components/mint-nft-button.tsx
- packages/wallets/README.md
- packages/wallets/src/api/client.ts
- packages/wallets/src/evm/types/wallet.ts
- packages/wallets/src/evm/wallet.ts
- packages/wallets/src/services/wallet-factory.test.ts
- packages/wallets/src/services/wallet-factory.ts
- packages/wallets/src/solana/types/wallet.ts
- packages/wallets/src/solana/wallet.ts
Made naming changes to spec, reverted `major` version and updated to `minor`. 
Updated anywhere in sdk that required changes.
Tests pass, functions/method names are updated to align with spec, version is still 0.x.x
> Wallets SDK: changes to spec

- .changeset/kind-pots-act.md
- .changeset/shy-turkeys-cry.md
- .changeset/twelve-masks-invite.md
Missed changeset in #1034 
None needed here
expo-demo: minor
auth-client: patch
react-native: minor
> Expo: missing changeset

- .changeset/nice-mayflies-knock.md
- .changeset/tall-fans-drum.md
- packages/client/ui/react-ui/src/index.ts
- packages/wallets/package.json
- packages/wallets/src/api/client.ts
- packages/wallets/src/api/types.ts
- packages/wallets/src/evm/wallet.ts
- packages/wallets/src/index.ts
- packages/wallets/src/openapi.json
- packages/wallets/src/solana/services/delegated-signers-service.test.ts
- packages/wallets/src/solana/services/delegated-signers-service.ts
- packages/wallets/src/solana/types/wallet.ts
- packages/wallets/src/solana/wallet.ts
- pnpm-lock.yaml
PR improves the typing around get delegate signers and get balances. Exposes two types that also get surfaced through the react-ui: `DelegatedSigner` and `WalletBalance`. 
Ensure tests pass, type names make sense.
> Delegate signers & balances: add types / errors

- .changeset/real-turtles-lick.md
- .changeset/stale-lamps-float.md
- apps/wallets/smart-wallet/next/src/app/_lib/providers.tsx
- apps/wallets/smart-wallet/next/src/app/wallet/page.tsx
- apps/wallets/smart-wallet/next/src/components/mint-nft-button.tsx
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.test.tsx
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
- packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
- packages/client/ui/react-ui/src/types/auth.ts
- packages/client/ui/react-ui/src/utils/dynamic/dynamicChainToCrossmintChain.ts
- packages/wallets/src/api/client.ts
- packages/wallets/src/evm/types/wallet.ts
- packages/wallets/src/evm/wallet.ts
- packages/wallets/src/services/types.ts
- packages/wallets/src/services/wallet-factory.test.ts
- packages/wallets/src/services/wallet-factory.ts
- packages/wallets/src/solana/services/approvals-service.test.ts
- packages/wallets/src/solana/services/approvals-service.ts
- packages/wallets/src/solana/services/transaction-service.test.ts
- packages/wallets/src/solana/types/wallet.ts
- packages/wallets/src/solana/wallet.ts
- Removed viem object from being extended from EVMSmartWallet. **(wallets-sdk)**
- Removed "chain" from constructor and into respective methods. **(wallets-sdk)**
- Removed "chain" property from CrossmintWalletProvider. **(react-ui)**
- Added getViemClient to EVMSmartWallet.
Tests pass, everything still works, demo updated, react-ui pkg changes integrated.
> Wallets SDK: minor release  (chain, getViemClient)

- .changeset/good-donkeys-sell.md
- apps/wallets/smart-wallet/next/src/app/wallet/page.tsx
- packages/wallets/src/api/client.ts
- packages/wallets/src/evm/services/delegated-signers-service.test.ts
- packages/wallets/src/evm/services/delegated-signers-service.ts
- packages/wallets/src/evm/types/wallet.ts
- packages/wallets/src/evm/wallet.ts
- packages/wallets/src/services/wallet-factory.ts
- packages/wallets/src/solana/types/wallet.ts
- packages/wallets/src/solana/wallet.ts
- Added`addDelegatedSigner` and `getDelegatedSigners` to our evm smart wallet.
- fixed bug with `unstable_getNfts`.
- added `chain` param to our evm `getBalances` method.
Manually tested flow with custom components from our quickstarts, added automated test for new delegate signer service file, tests pass! 
> Wallets SDK: EVM added delegate signer methods

- .changeset/forty-foxes-brush.md
- .changeset/neat-starfishes-glow.md
- packages/client/ui/react-ui/src/index.ts
- packages/wallets/src/evm/chains/index.ts
- packages/wallets/src/evm/index.ts
- packages/wallets/src/index.ts
Expose EVMSmartWalletChain type from react-ui
tests pass, types exported. 
> React sdk: expose EVMSmartWalletChain

- .changeset/ninety-numbers-stare.md
- packages/client/signers/src/communications/events.ts
- packages/client/signers/src/communications/schemas.ts
This PR
- Removes versioning from the events, will reintroduce if needed
- Adds device id 
Was tested e2e in the demo
> Signers events tuning

- .changeset/two-ligers-shake.md
- packages/client/signers/src/communications/schemas.ts
Just a small type fix from my previous PR
> NCS: small type fix

- .changeset/dull-paws-beam.md
> force fix npm version

- .changeset/heavy-hotels-flow.md
- .changeset/metal-shrimps-smile.md
- apps/wallets/smart-wallet/expo/app/signer.tsx
- packages/client/ui/react-native/src/providers/CrossmintRecoveryKeyProvider.tsx
- packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx
Some fixes that were missing for the quickstart:
- Better status to handle the full flow
- Fix a bad import
- Release rn-window
Tested with the expo app
rn-window: patch
> NCS: Small fixes to support quickstart

- .changeset/short-hornets-cough.md
- packages/client/ui/react-ui/src/providers/signers/CrossmintSignerProvider.tsx
Fixed issue when converting the admin signer public key response to base58
manually tested
> Experimental NCS: fix runtime err

- .changeset/sixty-beds-sin.md
- packages/client/ui/react-ui/src/hooks/useSignerInvisibleIFrame.ts
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
- packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
- packages/client/ui/react-ui/src/providers/signers/CrossmintSignerProvider.tsx
- packages/client/ui/react-ui/src/types/auth.ts
We need to change to the render deployment, the AWS one keeps failing randomly
> NCS: make iframe URL configurable

- .changeset/fair-snakes-mix.md
- packages/common/auth/src/types/user.ts
We enabled it server-side and were missing the type here.
Havent tested
common-auth: patch
> Auth: Expose Twitter ID

- .changeset/ten-seals-switch.md
- apps/payments/nextjs/pages/hosted-checkout/v3.tsx
- packages/client/base/src/types/hosted/v3/CrossmintHostedCheckoutV3Props.ts
Adding rules to Hosted v3 types. After adding this, the rules were being passed to the crossmint page successfully
Tested locally, combined with https://github.com/Paella-Labs/crossbit-main/pull/18631
> hosted: add appearance rules

- .changeset/lovely-points-hug.md
- apps/wallets/smart-wallet/expo/app/signer.tsx
- packages/client/ui/react-native/src/providers/CrossmintRecoveryKeyProvider.tsx
Wasnt fetching latest needsAuth in handleAuthRequried
Tested with expo app
> NCS: Fixes needAuth state

- .changeset/green-dodos-grow.md
- .changeset/mighty-bears-chew.md
- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
- packages/wallets/openapi-ts-error-1746815107172.log
- packages/wallets/src/evm/chains/index.ts
- packages/wallets/src/openapi.json
We have a client who needs shape
Only adding a new chain
common-base: patch
wallets: patch
> Wallets: Adds Shape to supported sdk chains

- .changeset/thick-bikes-talk.md
- packages/client/signers/src/communications/events.ts
- packages/client/signers/src/communications/schemas.ts
This PR introduces a new event as part of ongoing work to harden the `signers.crossmint.com` iframe.
n/a just adding some types and schemas to use in the iframe code base.
PATCH @crossmint/client-signers
> NCS: Get Status Event

- .changeset/old-hounds-work.md
- packages/client/ui/react-ui/src/providers/signers/CrossmintSignerProvider.tsx
If there's a device keyshare mismatch, route the user through the OTP flow again.
Master PR with full context [here](https://github.com/Crossmint/signer-frames/pull/20)
Refer to testing section in master PR listed above :)
"@crossmint/client-sdk-react-ui": patch
> NCS: Handle Device Key Share Mismatch (WAL-4558)

- .changeset/nasty-tips-smell.md
- packages/client/signers/src/communications/schemas.ts
- packages/client/ui/react-native/src/providers/CrossmintRecoveryKeyProvider.tsx
- packages/client/ui/react-ui/src/providers/signers/CrossmintSignerProvider.tsx
SDK part of the modification we agreed on for managing raw public keys instead of addresses
The change is basically
- `publicKey` type changes from string to `{bytes: string, encoding: Encoding, keyType: KeyType}` (consistent also with signatures)
- `signature` type changes from string to `{bytes: string, encoding: Encoding }` (maybe we should add here keyType too?)
- `address` changes to `publicKey` everywhere
When this integrates into the iframe, an end to end test will be performed
> NCS: Event adaptation

- .changeset/popular-windows-dream.md
- packages/client/signers/src/communications/schemas.ts
> NCS: fix return type

- .changeset/plenty-tomatoes-sneeze.md
- .changeset/stale-crabs-film.md
- packages/client/react-base/src/hooks/useWalletState.ts
- packages/client/ui/react-native/src/providers/CrossmintRecoveryKeyProvider.tsx
- packages/client/ui/react-ui/package.json
There were some messy dependencies triggering constant refreshes 
Tested on example expo app, but will need to test on quickstart
react-base: patch
> React Native: Fixes callback dependencies so they dont update constantly

- .changeset/silly-penguins-flow.md
- packages/client/base/src/lib/hosted-checkout/Order.ts
- packages/client/base/src/types/CryptoCurrency.ts
- packages/client/base/src/utils/ui.ts
- packages/common/base/src/blockchain/types/baseLayers.ts
- packages/common/base/src/blockchain/types/index.ts
- packages/common/base/src/blockchain/types/nft.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/wallets/src/openapi.json
Get that shit outta there
FISI
minor bump to:
- `@crossmint/client-sdk-base`
- `@crossmint/common-sdk-base`
- `@crossmint/wallets-sdk`
> remove cardano support

- .changeset/sour-apes-tie.md
- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
Add support for world chains
tested locally
> Feature: Support pay with WLD

- .changeset/stale-teachers-fry.md
- packages/client/signers/src/communications/events.ts
- packages/client/signers/src/communications/schemas.ts
- packages/client/ui/react-native/src/providers/CrossmintRecoveryKeyProvider.tsx
- packages/client/ui/react-ui/src/providers/signers/CrossmintSignerProvider.tsx
Adapting the interface of some iframe evenets
Will be tested end to end on the iframe update
> NCS: Add public key mapping to event response [WAL-4590]

- .changeset/nasty-jars-relax.md
- packages/client/signers/src/communications/events.ts
- packages/client/signers/src/communications/index.ts
- packages/client/signers/src/communications/schemas.ts
Just a new event for enabling exporting keys!
> NCS: `export-keys` event

- packages/wallets/src/solana/services/transactions-service.ts
- packages/wallets/src/utils/constants.ts
Adding backoff and reducing initial retry time
> SSW: tweak poll-for-confirmation retry time

- .changeset/thin-needles-exercise.md
- .changeset/wise-apes-walk.md
- apps/wallets/quickstart-devkit/app/providers.tsx
- apps/wallets/smart-wallet/next/README.md
- apps/wallets/smart-wallet/next/src/app/_lib/providers.tsx
- packages/client/react-base/src/types/wallet.ts
- packages/wallets/README.md
- packages/wallets/src/wallets/wallet-factory.ts
Make signer prop a mandatory field on both `getOrCreateWallet` and `createOnLogin`.
ensure ts throws error when missing signer from both definitions above.
> Wallets sdk: Non-optional Signer property

- .changeset/fast-turtles-deliver.md
- apps/wallets/quickstart-devkit/components/balance.tsx
- packages/wallets/src/api/client.ts
- packages/wallets/src/api/types.ts
- packages/wallets/src/openapi.json
- packages/wallets/src/wallets/wallet.ts
Migrate changes to new unstable balance api 
wallet balances work in a backwards compatible way and types are updated
> Wallet SDK 2.5: Migrate to new balance api

- .changeset/fuzzy-moose-cross.md
- .changeset/nasty-apes-guess.md
- apps/wallets/quickstart-devkit/components/activity.tsx
- apps/wallets/quickstart-devkit/components/balance.tsx
- apps/wallets/quickstart-devkit/lib/utils.ts
- packages/client/ui/react-ui/src/types/wallet.ts
- packages/wallets/src/api/client.ts
- packages/wallets/src/api/types.ts
- packages/wallets/src/wallets/types.ts
- packages/wallets/src/wallets/wallet.ts
Adds `experimental_activity` method to wallet class.
new method is marked as experimental
> Wallets sdk: Add new experimental activity method

- .changeset/cold-readers-draw.md
- .changeset/forty-fireants-care.md
- .changeset/great-planes-laugh.md
- apps/wallets/smart-wallet/expo/app/index.tsx
- apps/wallets/smart-wallet/expo/app/signer.tsx
- packages/client/react-base/CHANGELOG.md
- packages/client/react-base/src/hooks/useCrossmint.tsx
- packages/client/react-base/src/providers/CrossmintWalletProvider.tsx
- packages/client/ui/react-native/src/providers/CrossmintAuthProvider.tsx
- packages/client/ui/react-ui/src/hooks/useCrossmint.tsx
- packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
- packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
- packages/common/base/src/types/Crossmint.ts
- packages/wallets/package.json
- packages/wallets/src/openapi.json
- packages/wallets/src/signers/email/email.ts
- packages/wallets/src/wallets/wallet-factory.ts
- packages/wallets/src/wallets/wallet.ts
- pnpm-lock.yaml
We had many different errors picked up during testing, this fixes some of them
Will be testing with fintech quickstart
react-base: patch
common-base: minor
wallets: patch
> Wallets: Different fixes like error handling, renames customAuth and handling logout in RN

- .changeset/odd-feet-move.md
- packages/client/react-base/src/hooks/useWalletState.ts
- packages/client/react-base/src/providers/CrossmintWalletProvider.tsx
- packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
Clients prefer this and it feels more natural than depending exclusively on hooks
All tests pass
react-base: patch
> React: Makes getOrCreateWallet response from react include wallet instance

- .changeset/moody-poets-notice.md
- packages/client/ui/react-ui/src/hooks/useCrossmint.tsx
Fix a typescript complaint when using our CrossmintProvider.
(this same fix was used in our react-native package)
Error disappears 
> Fix CrossmintProvider type error

- .changeset/rich-flowers-cough.md
We've added support for Chrome Extensions in our backend, we also need to ship the new sdks that support it
None needed
react-base: patch
common-base: patch
> Changeset: extensionId changeset

- .changeset/orange-maps-trade.md
- packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx
- packages/client/ui/react-ui/src/providers/dynamic/DynamicWalletProvider.tsx
- packages/wallets/src/signers/email/email.ts
Cleanup and remove some console logs
na
@crossmint/client-sdk-react-native-ui
> Cleanup console logs

- .changeset/dull-pugs-smile.md
- apps/wallets/quickstart-devkit/app/providers.tsx
- apps/wallets/quickstart-devkit/components/balance.tsx
- apps/wallets/smart-wallet/expo/app/index.tsx
- packages/wallets/src/api/types.ts
- packages/wallets/src/wallets/types.ts
- packages/wallets/src/wallets/wallet.ts
Update the balance api to return a better format.
closes #[WAL-4879](https://linear.app/crossmint/issue/WAL-4879/update-balance-method)
Tested in quickstart sample
> Wallets sdk: Update balance api

- .changeset/six-owls-tickle.md
- packages/wallets/src/wallets/wallet.ts
> Fix silly balance bug 🤦‍♂️ 

- .changeset/calm-jobs-march.md
- packages/client/auth/src/CrossmintAuthClient.test.ts
- packages/client/auth/src/CrossmintAuthClient.ts
Postmortem document: https://docs.google.com/document/d/1IRJGFhjWInYVbRIbB6ctD714h-wvCgT0tHipDy4ELss/edit?usp=sharing
Tested against reproducible scenario
@crossmint/client-sdk-auth
> Crossmint Auth: fix stale session

- .changeset/flat-hornets-double.md
- .changeset/silent-taxis-turn.md
- apps/wallets/quickstart-devkit/app/providers.tsx
- apps/wallets/quickstart-devkit/hooks/useDynamicConnector.tsx
- apps/wallets/quickstart-devkit/hooks/usePrivyConnector.tsx
- packages/client/ui/react-native/src/index.ts
- packages/client/ui/react-ui/src/types/wallet.ts
- packages/wallets/src/wallets/evm.ts
- packages/wallets/src/wallets/solana.ts
> Wallets sdk: Fix wallet from constructor type

- .changeset/tidy-eyes-peel.md
- packages/client/signers/src/communications/urls.ts
Iframe server locally runs on port 54825 not 3000.
na
@crossmint/client-signers
> Fix local devt email signers iframe url

- .changeset/fuzzy-zoos-dream.md
- packages/wallets/src/signers/email/email-signer.ts
- packages/wallets/src/signers/email/evm-email-signer.ts
Add capability 
Tested with this react component: https://github.com/Crossmint/crossmint-sdk/pull/1235
> WAL-5151: Add EVM sign message

- packages/client/ui/react-ui/src/components/index.ts
- packages/client/ui/react-ui/src/components/signers/PhoneConfirmation.tsx
- packages/client/ui/react-ui/src/components/signers/PhoneOTPInput.tsx
- packages/client/ui/react-ui/src/components/signers/PhoneSignersDialog.tsx
- packages/client/ui/react-ui/src/components/signers/index.ts
- packages/client/ui/react-ui/src/icons/phoneOTP.tsx
- packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
Added react components for sms signing
Manual testing
> Adding react component for sms

- .changeset/selfish-buttons-worry.md
- packages/wallets/src/api/client.ts
Rollback to older activity api version. 
tested
> wallets sdk: fix activity api version

- .changeset/fresh-dryers-clap.md
- packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts
- packages/client/base/src/types/hosted/v3/CrossmintHostedCheckoutV3Props.ts
- packages/client/ui/react-ui/src/components/hosted/v3/CrossmintHostedCheckoutV3.tsx
- packages/common/base/src/types/index.ts
- packages/common/base/src/types/json.ts
> feat: checkout order metadata

- .changeset/smart-emus-pay.md
- packages/wallets/src/wallets/wallet.ts
Expose getTransaction method 
tested method manually 
> Wallets sdk: Add getTransaction method

- .changeset/great-impalas-refuse.md
- packages/client/rn-window/package.json
- packages/client/rn-window/src/rn-webview/RNWebView.test.tsx
- packages/client/rn-window/src/rn-webview/RNWebView.tsx
- packages/client/rn-window/vitest.config.ts
- packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx
- pnpm-lock.yaml
This PR prevents a possible code injection attack: https://linear.app/crossmint/issue/WAL-5210/high-potential-arbitrary-javascript-injection.  An attacker may manipulate their `appId` to inject code into our `RNWebView`.
```TS
// code produced in packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx, but running in RNWebView context
// Intended: window.crossmintAppId = 'legitimate-app-id';
// Malicious input: legitimate-app-id'; alert('XSS'); window.ReactNativeWebView.postMessage(JSON.stringify({type: 'steal', data: localStorage})); //
// Result: window.crossmintAppId = 'legitimate-app-id'; alert('XSS'); window.ReactNativeWebView.postMessage(JSON.stringify({type: 'steal', data: localStorage})); //';
```
The injected could steal JWTs and potentially key material, …
> Security: Fix Code Injection In React Native WebView (Resolves WAL-5210)

- .changeset/friendly-pandas-vanish.md
- packages/client/window/src/utils/safeUrl.ts
- packages/client/window/src/windows/NewTab.ts
- packages/client/window/src/windows/Popup.ts
> WAL-5336: safe url parsing

- .changeset/nasty-cougars-nail.md
- packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
local, can access camera + mic now
> embed: change iframe allows for persona

- .changeset/silver-worms-sparkle.md
- packages/client/ui/react-ui/src/components/signers/EmailOTPInput.tsx
Changed OTP to be 9 digits long
Manual testing
Large screen:
Small screen:
> 9 digist otp

- crossmint-sdk.code-workspace
- pnpm-lock.yaml
When we removed the react app we forgot to remove the workspaces path too.
na
> Remove smart wallet react app workspace

- .changeset/serious-terms-check.md
- packages/wallets/README.md
Updated wallets sdk readme 
closes: https://linear.app/crossmint/issue/WAL-5497/update-wallets-sdk-example-docs-to-include-experimental-customauthjwt
doc change makes sense
> Wal 5497 update readme

- .changeset/wild-lizards-think.md
- packages/wallets/src/wallets/evm.ts
- packages/wallets/src/wallets/solana.ts
- packages/wallets/src/wallets/types.ts
- packages/wallets/src/wallets/wallet.ts
Expose a method `approveTransaction`. 
Closes https://linear.app/crossmint/issue/WAL-5414/enable-approve-tx-for-external-approvals
tested with evm wallets
> Wallets SDK: Add approveTransaction

- .changeset/chilled-queens-double.md
- packages/wallets/README.md
- packages/wallets/src/signers/non-custodial/ncs-signer.ts
Clients are running into issues when setting up email signers, this pr attempts to improve the messaging around setting up the onAuthRequired method when not using our react/native package.
Error message shows up as expected when encounter issue.
> Wallets sdk: Improve error when missing onAuthRequired

- .changeset/rich-turkeys-unite.md
- apps/wallets/quickstart-devkit/app/providers.tsx
- packages/client/ui/react-ui/src/components/auth/methods/google/ContinueWithGoogle.tsx
- packages/client/ui/react-ui/src/components/auth/methods/google/GoogleSignIn.tsx
- packages/client/ui/react-ui/src/components/auth/methods/twitter/TwitterSignIn.tsx
- packages/client/ui/react-ui/src/hooks/useCrossmintAuth.ts
- packages/client/ui/react-ui/src/hooks/useOAuthWindowListener.ts
- packages/client/ui/react-ui/src/providers/CrossmintAuthProviderInternal.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.test.tsx
- packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.tsx
- packages/client/ui/react-ui/src/providers/auth/OAuthFlowProvider.tsx
Right now setting up headless oauth login is a pain because we need all our client-window listeners. This pr exposes that login method
EVM: Crossmint auth and BYOA (privy)
> React UI: exposes experimental_loginWithOauth

- .changeset/breezy-laws-melt.md
- packages/client/ui/react-native/package.json
- packages/client/ui/react-native/src/components/embed/v3/EmbeddedCheckoutV3WebView.tsx
- packages/client/ui/react-native/src/hooks/useCrossmintCheckout.tsx
- packages/client/ui/react-native/src/utils/eventEmitter.ts
- pnpm-lock.yaml
> rn: use crossmint checkout

- .changeset/heavy-readers-end.md
- apps/wallets/quickstart-devkit/app/home.tsx
- apps/wallets/quickstart-devkit/app/providers.tsx
- apps/wallets/quickstart-devkit/components/approval-test.tsx
- packages/wallets/src/utils/errors.ts
- packages/wallets/src/wallets/evm.ts
- packages/wallets/src/wallets/solana.ts
- packages/wallets/src/wallets/types.ts
- packages/wallets/src/wallets/wallet.ts
Create a unified approval method for both transactions and signatures. 
tested with adding delegate signers, and creating a testing component in devkit quickstart to test the approval process flow.
> Wallets SDK: Support a single approval method

- .changeset/ninety-otters-serve.md
- apps/wallets/quickstart-devkit/app/home.tsx
- apps/wallets/quickstart-devkit/components/firebase-phone-auth.tsx
- apps/wallets/quickstart-devkit/components/login.tsx
- apps/wallets/quickstart-devkit/lib/firebase.ts
- apps/wallets/quickstart-devkit/package.json
- packages/client/ui/react-ui/src/components/common/Dialog.tsx
- pnpm-lock.yaml
Added a firebase (byoa) phone signers example to our devkit. Also improved our a11y for our dialog component in our react package (small change why i left in here)
- Tested phone signer 
- tested a11y change
> Firebase phone signer + Dialog a11y

- .changeset/tasty-foxes-travel.md
- packages/common/base/src/types/errors.ts
Add more errors 
just adding thing to a const
```
---
"@crossmint/common-sdk-base": patch
---
Adding more payment error codes
```
> Payments: Add more errors

- .changeset/lucky-apricots-shop.md
- .changeset/smooth-snakes-applaud.md
- apps/wallets/quickstart-devkit/components/approval-test.tsx
- packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx
- packages/wallets/src/wallets/wallet.ts
Have to revert back to needsAuth being a state. When it's a ref, it doesn't update the state so remains false
Tested with demo expo app
wallets: patch
rn-ui: patch
> bug: Reverts back to needsAuth being a state

- .changeset/empty-bears-listen.md
- apps/wallets/quickstart-devkit/app/providers.tsx
- biome.json
- packages/common/base/src/blockchain/types/evm.ts
- packages/common/base/src/blockchain/utils/blockchainToCopyName.ts
- packages/common/base/src/blockchain/utils/evm/blockchainToChainId.ts
- packages/wallets/src/api/types.ts
- packages/wallets/src/chains/chains.ts
- packages/wallets/src/openapi.json
- packages/wallets/src/wallets/stellar.ts
- packages/wallets/src/wallets/wallet.ts
We are adding support for Flow in the API. This needs to be merged after.
No tests added
common-base: patch
wallets: patch
> feat: Adds Flow

- packages/wallets/src/openapi.json
- packages/wallets/src/wallets/wallet.ts
Regenerated the types for the sdk. Updated to use name for name and not symbol.
> Balance API: new types

- .changeset/long-spies-complain.md
Just changeset commit
No testing
> Balance api: changeset

- apps/payments/nextjs/package.json
- pnpm-lock.yaml
Not used package
Relying on CI/CD
> starter: remove unused packages

- .changeset/fluffy-pianos-confess.md
- packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx
Remove RN webView caching
Didn't test
> Fix: Remove rn caching

- .changeset/flat-dancers-camp.md
- packages/client/rn-window/src/rn-webview/Parent.ts
- packages/client/rn-window/src/transport/RNWebViewTransport.ts
- packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx
- packages/client/window/src/EventEmitter.ts
- packages/client/window/src/handshake/Child.ts
- packages/client/window/src/handshake/Parent.ts
Add temporary log and an attempt to reconnect when iframe disconnects
Crossing fingers
> RN: WebView re-creation

- .changeset/crossmint-auth-base-provider.md
> Fix: changeset package name

- .changeset/chilled-bananas-run.md
Changelog for https://github.com/Crossmint/crossmint-sdk/pull/1422
N/A
> Onramp: Added changelog for clientSecret
