Crossmint/crossmint-sdk

packages/ui/react-ui/src/CrossMintPopupProvider.tsx

Issue: https://github.com/Paella-Labs/crossbit-main/issues/238
Long story short: It was crashing when the title or description for the collection had special characters such as “
The root cause is that we were only encoding the parameters inside the callbackUrl once. So when on the backend side we decoded the callbackUrl parameter, its own query parameters were absolutely decoded as well. They should instead still be encoded "once" so that when the customer is redirected to that callbackUrl they are properly handled.
So now we encode the callbackUrl parameter (once) but also its own parameters again (so "twice") so that they are decoded once first and then twice.

Fixed special characters used in callbackUrl query parameters

---

packages/ui/react-ui/src/CrossMintStatusProvider.tsx

Addresses #14 
We're getting hammered with requests from folks integrating crossmint who haven't yet added their own client ID
This just checks for the most common cases where it's not yet set, and throws a warning instead of trying to call the API

Stop making API requests with unset client ID

---

packages/ui/react-ui/src/CrossMintButton.tsx

Hey guys!
It looks like we were not including the className provided by the user into `CrossMintButton`. 
This should do.
Thanks! 🙏

react-ui - Include custom className

---

packages/ui/react-ui/package.json

Hey guys!
It looks like the postbuild script was failing when trying to create the package.json in both `cjs` and `esm` folder, and was producing invalid json:
Now it should output the format correctly.
Thanks! 🙏

react-ui - fix postbuild script

---

README.md
packages/ui/react-ui/package.json
yarn.lock

Hey, 
For the changelog, how about we add a tool that will take care of it for us in every version bump? It would create a CHANGELOG.md file that would look like:

Adding auto-changelog

---

packages/ui/react-ui/__tests__/CrossmintStatusButton.spec.tsx
packages/ui/react-ui/src/CrossmintStatusButton.tsx
packages/ui/react-ui/src/types.ts

It adds a few extra props on the Status button:
- `launchpadId` to keep track of which we are coming from. It would be added on the onboarding endpoint as a query param
- `configMint` object to store specifics for each implementarion/chain/launchpad. This follows the same philosophy that the same field in the Pay button (no client side validation for now)
Also:
- Little refactor on the way we build the onboarding url
- Unit tests to ensure everything keeps working 😅 
Thanks!

Add launchpad id and mintConfig props

---

packages/ui/vanilla-ui/src/CrossmintPayButton.ts

Adding parts for outside styling for web component. See `::part()` [specification](https://developer.mozilla.org/en-US/docs/Web/CSS/::part).

Add parts to Vanilla UI pay component

---

packages/ui/vanilla-ui/src/CrossmintPayButton.ts
packages/ui/vanilla-ui/src/CrossmintStatusButton.ts

Its a better practice to have spans inside the buttons.

Replacing p for span in vanilla ui buttons

---

packages/core/base/src/models/types.ts
packages/core/base/src/services/crossmintModalService.ts
packages/ui/react-ui/src/CrossmintPayButton.tsx
packages/ui/vanilla-ui/src/CrossmintPayButton.ts

Petition from magic eden: users should be able to tap / click on overlay and keep browsing. Adding new prop `dismissOverlayOnClick` to achieve that.

Add dismiss overlay on click

---

packages/core/base/src/services/crossmintModalService.ts
packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx

I kept the API surface of the button to remain as `ETH`, so its backwards compatible, and then we just make it lowercase in the query params.
Ideally we should probably make a new enum like the `Currency` we have in Crossmint, but it may not be worth it since all client would need to update their buttons if they upgrade package versions

Use same letter case as on Crossmint side

---

packages/core/base/src/models/types.ts
packages/core/base/src/services/crossmintModalService.ts
packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
packages/ui/react-ui/src/CrossmintPayButton.tsx
packages/ui/vanilla-ui/src/CrossmintPayButton.ts

This PR adds the PAY-766 Adding `successCallbackURL` and `failureCallbackURL` params to the query params.
It was tested with the test UI starter project.

PAY-766 Adding successCallbackURL and failureCallbackURL params to the query params

---

packages/core/base/src/models/types.ts
packages/core/base/src/utils/ui.ts
packages/core/base/src/utils/validate.ts
packages/core/base/src/utils/validateUUID.ts
packages/ui/react-ui/__tests__/CrossmintCollectionView.spec.tsx
packages/ui/react-ui/__tests__/CrossmintNFTDetail.spec.tsx

A few changes here:
- In the walletCollection view, in the wallets interface, replace address for `publicKey`, which is what is return in our endpoint.
- Remove the projectId everywhere as requested by @alfonso-paella (https://crossmint.slack.com/archives/C04SF1PBR7W/p1678769820170049)
Not changing anything about the nft interface, since I want it to be the same for all nfts regarding the chain.

Change wallet UI api

---

packages/core/base/src/models/types.ts
packages/core/base/src/utils/ui.ts
packages/ui/react-ui/__tests__/CrossmintNFTDetail.spec.tsx

Using chain names instead of shortened versions for NFT locator:
`sol:1235` -> `solana:12345`

Using chain names for NFT locators

---

packages/core/base/src/index.ts
packages/core/base/src/models/events.ts
packages/core/base/src/models/types.ts
packages/core/base/src/services/crossmintModalService.ts
packages/ui/react-ui/src/CrossmintPayButton.tsx
packages/ui/vanilla-ui/src/CrossmintPayButton.ts

This PR does two things:
- Adds an events type with all checkout events.
- Watches from events sent from the popover (crossbit-main).
That way, users will be able to subscribe to events that we will sent in different stages of the mint.
See demo:
https://www.loom.com/share/ee069a333abc4659a70bc82e7dfa2d50

Add on event prop

---

packages/core/base/src/index.ts
packages/core/base/src/models/events.ts
packages/core/base/src/models/paymentElement.ts
packages/core/base/src/services/crossmintPaymentService.ts
packages/starter/vue-ui-starter/package.json
packages/starter/vue-ui-starter/src/App.vue
packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue

OK so here it comes. 3 things this does on CrossmintPaymentElement component:
1. Rendering Iframe with /sdk/page
2. Listening to events from iframe, and emit them to `onEvent`
3. Emit event when recipient changes

Events and service

---

packages/core/base/src/models/paymentElement.ts

Modify price types to remove items.
Also adding missing CheckoutEvents types to PaymentEventMap so it can be used correctly (without the whole enum it was erroring out) They will be empty object for now.

Modify price types and include missing Checkout types to PaymentEventMap

---

packages/starter/vue-ui-starter/src/components/PayWithCC.vue
packages/ui/react-ui/src/CrossmintPaymentElement.tsx
packages/ui/react-ui/src/index.ts

Adding the payment element component to the React package.
Used chatGPT to convert the component from vue to react 🤯 
Tested it on react starter. Working great.

Add Payment Element in React

---

packages/core/base/src/models/errors.ts

Adding a generic error for transaction failure for now.
More context here: https://crossmint.slack.com/archives/C04SC413XMZ/p1680177719188949

Add generic transaction failure error

---

crossmint-client-sdk.code-workspace

Completely optional to use, but if u want this interface all you have to do is open the `crossmint-client-sdk.code-workspace` file
If you dont want to use it, you just continue to use your vscode as you normally do
imo, makes it significantly easier to browse the repo tho
When you open a terminal you also get to select which scope to open it in, so it saves you a bunch of `cd`ing to the correct directory

feat: Adds VSCode workspace file

---

packages/core/base/src/models/paymentElement.ts

Adding a new field `paymentMethodType` with three possible values for now:
`credit-card`, `google-pay` and `apple-pay`
We will need to think in the future what values this field will take for crypto payments. But for now, I'd say we are good.

Add payment method type to order finished event paylod

---

packages/core/base/src/models/errors.ts

Adding contract reverted generic error. This will be used to handle some contract reverted errors.

Add error execution reverted generic

---

packages/ui/react-ui/src/CrossmintPaymentElement.tsx

Avoid React component to re-render when recipient changes via the getIframeUrl function.

Fix react component

---

packages/core/base/src/services/crossmintPaymentService.ts
packages/core/base/src/services/crossmintUiService.ts
packages/ui/react-ui/src/CrossmintPaymentElement.tsx
packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue

re-rendering payment element ,  react registers multiple message event listener and fires duplicate message event.  and causes high resource consumption.

Remove event listener support

---

packages/ui/vanilla-ui/src/CrossmintPaymentElement.ts
packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue

Updated Vue and Lit component to remove event listeners on unmount. This is essentially doing the same thing #219 did for the React component. Covers bug #224.

Remove event listeners when unmounting the Lit and Vue component.

---

packages/core/base/src/models/errors.ts

new MINTO_INVALID in CrossmintErrors for ENS Domains Support in embedded checkout.

new MINTO_INVALID in CrossmintErrors

---

packages/ui/react-ui/src/types.ts
packages/ui/vanilla-ui/src/types.ts

The endpoints for the CrossmintStatusButton have been removed from crossmint-main, we should officially deprecate and remove all the related code in our client sdk

Remove and deprecate CrossmintStatusButton from client-sdk

---

packages/core/base/src/models/types.ts
packages/ui/react-ui/__tests__/CrossmintPayButton.spec.tsx
packages/ui/react-ui/src/CrossmintPayButton.tsx
packages/ui/vanilla-ui/src/CrossmintPayButton.ts

- new prop `getButtonText(connecting:boolean, paymentMethod:PaymentMethod)` allowing devs to custom control the text from js
Tested locally, added new unit test

pay button: custom text prop

---

packages/core/base/src/consts/embed.ts
packages/core/base/src/services/embed/crossmintPaymentService_OLD.ts
packages/starter/vue-ui-starter/src/components/PayWithCC.vue
packages/ui/react-ui/src/components/embed/crypto/CryptoEmbeddedCheckoutIFrame.tsx
packages/ui/react-ui/src/components/embed/fiat/FiatPaymentElement_OLD.tsx
packages/ui/vanilla-ui/src/components/embed/CrossmintPaymentElement.ts
packages/ui/vue-ui/src/components/CrossmintPaymentElement.vue

Adds support for multi language and multi currency on old fiat embedded checkout.

i18n: Fiat embedded checkout

---

packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
packages/client/wallets/aa/src/types/Config.ts
packages/client/wallets/aa/src/utils/signer.ts

Added WalletId and DeviceId as an optional parameter on the getOrCreate NCW method. If both of them are defined it will skip the call to crossmint to retrieve this data. 
Create a SCW using Fireblocks signer
Retrieve the SCW previously created using the deviceId and walletId as a parameter.

WAL-1481: Optional WalletId and DeviceId params 

---

packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts

We no longer use sandbox anywhere. It's always a "production" env, even if it's one of our demo workspaces that only allows testnet
Test locally hooked up SCW demo to this version of SDK

Prod keys: no more sandbox

---

packages/client/wallets/aa/package.json
yarn.lock

Updated ZeroDev SDK version to fix the transaction of native token.
Create an SCW using the SDK
Send a transaction:
```
const transaction = {
to: '0x123abc', // Recipient address
value: parseEther('0.2'), // Amount to send (in Wei)
};
console.log({ transaction });
console.log('Sending Tx');
const { hash } = await aaWallet.sendTransaction(transaction);
console.log({ hash });
```

WAL-1471: Updated ZD SDK version

---

packages/client/wallets/aa/src/blockchain/wallets/FireblocksNCWallet.ts
packages/client/wallets/aa/src/storage/LocalStorageRepository.ts
packages/client/wallets/aa/src/storage/index.ts

WalletId, DeviceId and Address of the NCW are now stored on the DB. 
In the parts of the code where this data is needed we first check if this already exists in the localstorage to skip a call to Crossmint
The Keys starts with 'NCW-'. The user can delete them using the purge data functionality on log out.
Use the SDK using a Fireblocks Signer and create or retrieve the SCW. Info should have been stored on the localstorage of the browser.

WAL-1398: Store user data on localstorage, not only on database

---

packages/client/wallets/aa/src/blockchain/wallets/BaseWallet.ts

Changed signMessage implementation to use 'signMessageWith6492' from ZeroDev Kernel. With that change now a message can be signed and verified even if the SCW is still no deployed.
Tested on the SDK before and after deploy:
```
const signature = await aaWallet.signMessage('TEST');   
const verified = await aaWallet.verifyMessage('TEST', signature);   
console.log({ verified });
```

SCW-68: Verify Signature. Fix signMessage with 6492.

---

packages/common/base/package.json
packages/common/base/src/utils/apiKey/validateAPIKey.ts
yarn.lock

use tweetnacl instead of noble, because noble doesnt compile to cjs
api key tests pass

api keys: use tweetnacl

---

packages/common/base/package.json

`vitest` on its own runs in 'watch' mode, so when I tried to run the release script, testing never finished to proceed
ran `yarn test` locally on the root folder and see that the 3 packages all test and complete

update test command

---

packages/client/ui/react-ui/package.json
packages/client/verifiable-credentials/package.json
packages/client/verifiable-credentials/src/verification/services/nftStatus.ts
yarn.lock

This PR addresses a build failure due to an improper import statement. The issue arises from the use of import { EVMNFT } from "@crossmint/client-sdk-base"; which is incorrect. The correct import should come from the @crossmint/common-sdk-base package.
By updating the import statement, we aim to resolve the TypeScript error TS2345 that was preventing the build process from completing successfully. This change is integral to ensuring that the codebase remains stable and that the build processes run without errors.
Also we modified the imports to the latest versions of the client-sdk.
Run `yarn build`

SCW-326: Fixed yarn build

---

packages/client/wallets/aa/src/blockchain/wallets/BaseWallet.ts
packages/client/wallets/aa/src/utils/error.ts

**Improved Error Handling in Token Transfers:**
In the `transfer` function, we now check the `status` of the transaction receipt. If the transaction is successful (i.e., `status === 1`), the function returns the transaction hash as before. However, if the transaction fails (`status !== 1`), it now throws a TransferError with a descriptive message including the token ID and the transaction hash. This makes it easier to debug issues with token transfers as it provides more context about the failure.
**Refined Transaction Error Handling:**
In the `sendTransaction` method, we've implemented a try-catch block. If an error occurs while sending the transaction, instead of allowing it to propagate up as a generic error, the method now catches the error and throws a `TransactionError`. This …

SCW-300 Check status tx

---

packages/client/base/src/types/embed/crypto.ts
packages/client/base/src/utils/embed/updatableParams.ts
packages/client/ui/react-ui/src/components/embed/crypto/CryptoEmbeddedCheckoutIFrame.tsx

Related with -> https://github.com/Paella-Labs/crossbit-main/pull/11326
Added a new parameter to pay with crypto so it can be used to specify the network the dev wants the user to pay with
Example usage:
Tested e2e with https://github.com/Paella-Labs/crossbit-main/pull/11326

PayWithL2: Added 'network' parameter to pay with ETH

---

packages/client/base/src/types/embed/crypto.ts
packages/client/base/src/types/events/internal/events.ts
packages/client/base/src/types/events/internal/payloads.ts
packages/client/base/src/utils/embed/updatableParams.ts
packages/client/ui/react-ui/src/components/embed/crypto/CryptoEmbeddedCheckoutIFrame.tsx

Context: https://crossmint.slack.com/archives/C06CV64AS6M/p1707460963467259?thread_ts=1707339734.618149&cid=C06CV64AS6M
Tested e2e all parameters

PayWithL2: Renamed parameters

---

packages/client/base/src/services/embed/crossmintIFrameService.ts

In embedded checkout we need to know whether the function handleSwitchChain is defined or not, and right now this JSON.parse just hides it completely. So the proposed solution is to keep the functions there so we can check for it later on crossmint-main side, as the signer is sent as a JSON string completely
Tested e2e that the switch change request is triggered

PayWithL2: Sending whether handleSwitchChain is used

---

packages/client/wallets/aa/src/services/logging/index.ts

Catching an error on the logging service file. 
DatadogProvider uses the variable 'window' and it crashes when using the SDK on a frame from Crossbit (Adding passphrase modal on Crossmint Connect to recover the wallet )
Tried to put a condition like  `if (!window)`  or `if (typeof window == "undefined")` but it was throwing the same error. 
Using the SDK to recover the AA Wallet using Crossmint Connect

SCW-344: Fix 'wallet is not defined' error

---

packages/client/wallets/aa/src/services/logging/index.ts

Revert SDK modification. SDK, as a front package, should have the DatadogLogger provider. Solution implemented on Crossbit 
Test WC and CC using SDK current version

SCW-344: Revert "SCW-344: Fix 'wallet is not defined' error"

---

packages/client/wallets/walletconnect/src/hooks/useWalletConnectSessions.tsx
packages/client/wallets/walletconnect/src/utils/walletconnect/mockRequiredNamespaceMethods.ts

mock the required namespace methods, if the wallet doesnt support them
this improves compatibility, because we can "get in the door" (aka connect, maybe sign a message) with any website - and later if the site tries to use an unsupported method, we will show an "Unsupported method requested" modal
not implemented, modal coming later
mocks required methods correctly

wc: mock required namespace methods

---

packages/client/starters/vue-ui-starter/src/components/PayWithCC.vue
packages/client/ui/vanilla-ui/package.json
packages/client/ui/vanilla-ui/src/components/embed/CrossmintPaymentElement.ts
packages/client/ui/vue-ui/package.json
packages/client/verifiable-credentials/package.json
packages/client/wallets/aa/front/package.json
packages/client/wallets/walletconnect/package.json
yarn.lock

no reason to not sync these deps with the latest versions, due to syncing yarn.lock doesnt update much - if didnt sync, would be a couple hundred lines
ci passes, `yarn install` doesnt update lock file

fix: lock and sync deps

---

packages/client/wallets/aa/package.json
packages/client/wallets/aa/src/CrossmintAASDK.ts
yarn.lock

ZeroDev depends on infura. This adds another layer of dependencies which we don't control. We submit our own rpcs now.
ZeroDev's code:
where `CHAIN_ID_TO_NODE` looks like this (and more):
Manual Testing creating and retrieving wallets.

Use our own rpc urls instead of zerodevs default (infura)

---

packages/client/wallets/aa/src/blockchain/wallets/BaseWallet.ts
packages/client/wallets/aa/src/utils/index.ts
packages/client/wallets/aa/src/utils/transactions.ts

/**
* We need to support odd value and data fields in a tx, as that data comes from WC
* ZeroDev implements hexlify, but doesn't support to send an odd string in value or data fields
* so we need to make the hexlify fix manually when sending a transaction.
* That fix can be found here:
* https://github.com/ethers-io/ethers.js/commit/a12030ad29aa13c02aa75d9e0860f4986a0043b4#diff-047e7ebfdbd5c41e762cda03593bd15ed8b3121dece67262729dfcbde7040818R221
* And more context on this issue:
* https://github.com/ethers-io/ethers.js/issues/614
*
* Applying to it hexValue is used as a workaround on Crossbit, but doesn't cover all the cases (i.e. 0x71afd498d0000).
* This function is the same as hexValue but without hexStripZeros, which is what makes it to not work.
*/
Described in this PR: …

WC-AA: Add workaround to support odd values on sendTransaction

---

packages/client/ui/react-ui/src/components/hosted/index.ts
packages/client/window/package.json
packages/client/window/src/EventEmitter.ts
packages/client/window/src/handshake/Parent.ts
packages/client/window/src/utils/generateRandomString.ts
yarn.lock

Add the verification SDK into the bundle. Also, removes the `nanoid` dependency. It was introducing the `crypto` package that was conflicting with the react starter. This was the error:
```
Module not found: Error: Can't resolve 'crypto' in '/Users/pablogarciaegido/Desktop/code/paella/crossmint-client-sdk/packages/client/ui/react-ui/dist'
BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
If you want to include a polyfill, you need to:
- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
resolve.fallback: { …
```

verification-sdk: add to bundle

---

packages/client/base/src/utils/i18n/dictionaries/jaJp.ts

The translations file was misformatted. This caused an issue in Storefront in staging. https://app.datadoghq.com/dashboard/4zb-6wt-t6r/console-dashboard?query=%22ERROR_BOUNDARY_STOREFRONT_FRONTEND%22&event=AgAAAY4bzUUeUDuOGgAAAAAAAAAYAAAAAEFZNGJ6YmJ2QUFDcE52djExcHF6ZVFBQQAAACQAAAAAMDE4ZTFjMzctYzExZi00YWFmLWIyYTItNjY0MTgxODMxOWZk&fromUser=false&index=%2A&panelFrom=1709863200000&panelTo=1709865000000&panelType=logs&refresh_mode=sliding&view=spans&from_ts=1709712085712&to_ts=1709884885712&live=true
Tested in starter:

jp: fix translations

---

packages/client/ui/react-ui/src/components/hosted/CrossmintPayButton.tsx
packages/client/ui/react-ui/src/components/hosted/CrossmintVerificationButton.tsx

For consistency, using the same strategy as with the CrossmintPayButton for styling.
Users will be able to pass:
- Classes
- Styles
- Text content
Tested locally in starter. High level customisation.

verification-sdk: Styling and text content props

---

packages/client/wallets/aa/package.json
yarn.lock

Viem has not kept older versions of the sdk up to date with new chain object. ZeroDev workaround: more info here: https://crossmint.slack.com/archives/C052QC5JGSD/p1710438324044929
Manual testing

Version bump to add support for astar

---

packages/client/wallets/aa/src/index.ts

Get us back to the agreed upon API surface
Linked locally and could do 
```
import { Blockchain } from '@crossmint/client-sdk-aa';
Blockchain.POLYGON
```
as the docs say

add Blockchain alias [Fixes SCW-454]

---

packages/client/window/src/EventEmitter.ts
packages/client/window/src/handshake/Child.ts
packages/client/window/src/handshake/Parent.ts
packages/client/window/src/handshake/index.ts
packages/client/window/src/windows/Child.ts
packages/client/window/src/windows/IFrame.ts
packages/client/window/src/windows/Popup.ts
packages/client/window/src/windows/index.ts

change some protected fields to public - this allows changing the targetOrigin manually, for ex if the origin of the iframe/window changes while being open (ex: oauth flow)
also allows passing initial different origin from the url for the window, again for ex oauth where original url is stytch.com but events will come from crossmint.com
tested with auth sdk poc

window pkg: change fields + targetOrigin param

---

packages/client/wallets/aa/package.json
packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts

In the[ WC build](https://github.com/Crossmint/crossmint-sdk/actions/runs/8329424732/job/22791687611?pr=437), we're having this error:
`Error: src/wallets/WalletConnectEVMAAWallet.ts(9,5): error TS2742: The inferred type of 'getSupportedChains' cannot be named without a reference to '@crossmint/client-sdk-aa/node_modules/@crossmint/common-sdk-base'. This is likely not portable. A type annotation is necessary.`
It looks like a [bug from Typescript](https://github.com/microsoft/TypeScript/issues/42873#issuecomment-1990995016) (that comment is from last week). 
How it applies to our situation:
// Base
`export { BlockchainIncludingTestnet }`
// AA
```
import { BlockchainIncludingTestnet }
...
export { EVMAAWallet } from  'Base'
```
// WC SDK
``` 
import { EVMAAWallet } from 'AA' // => uses …
```

fix WC issue

---

packages/client/wallets/walletconnect/package.json
packages/client/wallets/walletconnect/src/utils/walletconnect/prettifyWalletConnectChain.ts

We were importing `blockchainToCopyName`, when the actual function was `blockchainToDisplayName`.
Also, started adding `yalc` commands to make our life easier when connecting packages locally. This only Impacts locally when running the app 
Make a successful connection using WC SDK.![Screenshot 2024-03-18 at 12 40 06 PM](https://github.com/Crossmint/crossmint-sdk/assets/132915515/9db0244e-2f8e-4511-af75-dd9356dac15b)

WC SDK: Fix library imported from base

---

packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts

Llama RPC caused a `net_version` error. Changing the url resolves it
Created AA locally

AA: Fix Base RPC

---

packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts

This PR drops the `getPaymasterMethod` from `EVMAAWallet`. You can see [here](https://github.com/Crossmint/crossmint-sdk/pull/456) that it was added:
- For use internally
- Wasn't intentionally exposed.
I'd normally make it private, but since it's no longer used just deleting it instead.
TS Compiles & Existing Tests

Simplification: Drop Unused (and unnecessarily exposed) Paymaster Method

---

packages/client/wallets/aa/src/blockchain/token/Tokens.ts
packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts

Given that it's unlikely we'll be supporting Cardano or Solana token transfers from our AA SDK anytime soon, this PR drops them.
TS Compiling & existing tests

Simplification: Drop Unused Token Types

---

packages/client/wallets/aa/src/CrossmintAASDK.ts
packages/client/wallets/aa/src/api/CrossmintWalletService.ts
packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
packages/client/wallets/aa/src/types/API.ts

`setCustodianForTokens` in `EVMAAWallet` is not ready for use, and we don't  have plans to support this T. There's no sense exposing it or keeping it within the SDK.
TS Compiling and Existing Tests
Created a new wallet and minted an NFT on the `w3a-main` branch locally (w/ a few small changes to accomidate other changes to the sdk)

Simplification: Drop Custodian Session Key Pt. 1

---

packages/client/wallets/aa/src/CrossmintAASDK.ts
packages/client/wallets/aa/src/api/CrossmintWalletService.test.ts
packages/client/wallets/aa/src/api/CrossmintWalletService.ts
packages/client/wallets/aa/src/blockchain/wallets/eoa.ts
packages/client/wallets/aa/src/types/API.ts
packages/client/wallets/aa/src/utils/error.ts

This PR:
- Stops session keys from being created with new AA wallets in conjunction with  https://github.com/Paella-Labs/crossbit-main/pull/13254.
- For these session keys have any effect, the user must sign.
- We've removed the method to do that from the SDK, since it's not ready yet.
- When/if we re-enable, we'll include custodial session key (A FB vault on CM Backend) creation within the method, not upon wallet creation.
- In anticipation of passkeys, organizes EOA wallet creation into a `EOAWalletService` class.
TS Compiling + Existing Tests
Will test E2E before merging once the `crossbit-main` PR lands

Simplification: Drop Custodian Session Key Pt. 2

---

packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
packages/client/wallets/aa/src/blockchain/wallets/paymaster.ts

This PR:
- moves the paymaster middleware definition outside of the constructor to make `EVMAAWallet` more minimal
- Consolidates paymaster functions into a new `paymaster.ts` file
Locally tested web3auth flow, tx was sponsored as expected.
TS compiling + existing tests

Simplification: Consolidate Paymaster Pieces

---

packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
packages/client/wallets/aa/src/utils/blockchain.ts

For certain chains, Zerodev uses Gelato to send transactions. If that's the case, we need to provide:
```TypeScript
...{
maxFeePerGas: "0x0"
maxPriorityFeePerGas: "0x0"
}
```
Within transaction and userOp parameters. [source](https://docs.zerodev.app/sdk/faqs/use-with-gelato#transaction-configuration)
Somewhere along the way EIP1559 may have been conflated w/ the Gelato situation, coincidentally, this has worked fine so far because polygon CDK chains, which ZD uses Gelato for, don't support 1559. This PR clarifies this logic, which is useful for other things I'm working on.
Locally, I confirmed that the package still works on the demo repo on branch `main-w3a` by signing in and minting
Passkey Release QA, which will include testing polygon CDK chains.
TS Compiling & Existing Tests.

Simplification: Gelato Bundler Special Case

---

packages/client/wallets/aa/src/blockchain/wallets/EVMAAWallet.ts
packages/client/wallets/aa/src/blockchain/wallets/smartAccount.ts
packages/client/wallets/aa/src/utils/blockchain.ts

Context here is that we're in the process of minimizing our API surface, including removing the redundant methods:
- `EVMAAWallet.sendTransaction`
- `EVMAAWallet.signMessage`
- `EVMAAWallet.signTypedData`
In favor of letting developers using a `walletClient` we expose directly instead.
In order to completely replace these methods, we need to add some error handling & logging to the `walletClient` we expose. This PR:
- Creates a minimal wrapper over `SmartAccountClient` to show how we'll do this
- Updates `getSigner` to return a `SmartAccountClient` rather than a `KernelAccountClient` since our API should aim not to expose provider specific types.
Within the PRs that remove the methods I mention above, we'll replace any functionality within this wrapper.
Local Testing on SCW Demo on branch …

Simplification: Smart Account Client Handling & Types

---

packages/client/wallets/aa/src/CrossmintAASDK.test.ts
packages/client/wallets/aa/src/SmartWalletSDK.ts
packages/client/wallets/aa/src/blockchain/wallets/EVMSmartWallet.ts
packages/client/wallets/aa/src/blockchain/wallets/eoa.ts
packages/client/wallets/aa/src/types/Config.ts

This PR makes a couple adjustments according to the latest iteration of our SDK design:
- Renames `getNFTs` to `nfts` on the `EVMSmartWallet` class
- Update SDK init parameter type, renaming the property `apiKey` to `clientApiKey`
- Adds a few jsdoc comments
Passkey Release QA
TS Compiling & Existing Tests

Passkeys Release: Core SDK Updates

---

packages/client/wallets/aa/package.json
packages/client/wallets/aa/src/utils/signer.ts

We're importing a huge package to wrap the `IProvider` that `web3auth` gives us, but it's not needed! This PR:
- Fixes that
- Drops `web3` from our deps
Manually, within the SCW_DEMO repo, on a fork of the `main-w3a` branch that accommodates the latest SDK changes, I:
- Signed in and minted an NFT.
- Confirmed the address of the signer.

Simplification: Drop `web3` Dependency.

---

packages/client/wallets/aa/src/api/BaseCrossmintService.ts
packages/client/wallets/aa/src/api/CrossmintWalletService.test.ts
packages/client/wallets/aa/src/blockchain/BlockchainNetworks.ts
packages/client/wallets/aa/src/blockchain/wallets/EVMSmartWallet.ts
packages/client/wallets/aa/src/blockchain/wallets/eoa.ts
packages/client/wallets/aa/src/blockchain/wallets/passkey.ts
packages/client/wallets/aa/src/blockchain/wallets/paymaster.ts
packages/client/wallets/aa/src/utils/blockchain.ts
packages/client/wallets/aa/src/utils/index.ts

When using the SDK I've noticed we (unintentionally?) surface many unnecessary parts. This makes the surface of the SDK huge and easy to break.
This PR:
- Removes all our constants (`ZD_AMOY_PROJECT_ID`, etc) from the package export
- Drops an unused function.
Build passing & existing tests + passkey release QA

Simplification: SDK Surface Audit 1

---

packages/client/verifiable-credentials/package.json
packages/client/verifiable-credentials/src/presentation/getCredential.test.ts
packages/client/verifiable-credentials/src/presentation/getNfts.test.ts
packages/client/verifiable-credentials/src/services/lit.test.ts
packages/client/verifiable-credentials/src/verifiableCredentialsSKD/types/verifiableCredential.ts
packages/client/verifiable-credentials/src/verifiableCredentialsSKD/verification/signature.test.ts
packages/client/verifiable-credentials/src/verifiableCredentialsSKD/verification/signature.ts
packages/client/verifiable-credentials/src/verifiableCredentialsSKD/verification/verify.test.ts
packages/client/verifiable-credentials/src/verifiableCredentialsSKD/verification/verify.ts
yarn.lock

Update VCs to W3C 2.0 standard:
Add name and description optional fields
dates are now :"validFrom" and "validUntil"
"validUntil" is optional
removed outdated Krebitdao lib
Unit tests

VC: Use vc 2.0

---

packages/client/wallets/aa/src/types/Config.ts

This PR makes sure that the Type that appears in the preview for `SmartWalletSDK.getOrCreateWallet` for user parameters is `UserParams` instead of `WhitelabelUserParams`.
TS Compiling + Existing Tests

Smart Wallets: Update User Param Type & Preview

---

yarn.lock

It's impossible to install dependancies using node 20 right now. The error lists the dependency responsible, so I tracked down it's parent a few layers up, uninstalled and reinstalled to upgrade `^x.x.x` dependancies.
```bash
nvm use 20
yarn install
```

Fix: Installs While Using Node 20

---

packages/client/wallets/smart-wallet/src/blockchain/wallets/EVMSmartWallet.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/service.ts
packages/client/wallets/smart-wallet/src/types/internal.ts

This PR:
- Changes `EVMSmartWallet` to be provider agnostic, and cleans up the constructor, which had too much going on.
- Makes setting up error handling easier.
Went through the demo minting flow.
Existing tests + CI

Smart Wallet: Make `EVMSmartWallet` Provider Agnostic

---

packages/client/wallets/web3auth-adapter/package.json
packages/client/wallets/web3auth-adapter/src/index.ts

This PR:
- Removes a redundant parameter from the `getWeb3AuthSigner` function.
- Exports some essential types for using the function from the package.
Locally, within the demo site create a new web3auth wallet.

Smart Wallets: Web3Auth Adapter Iteration

---

.changeset/lemon-grapes-pretend.md
apps/payments/nextjs/pages/payment-element/fiat.tsx
packages/client/ui/react-ui/src/components/embed/fiat/FiatEmbeddedCheckoutIFrame.tsx

i have no idea how this was not found earlier, but this was introduced [here](https://github.com/Crossmint/crossmint-sdk/pull/397/files) - the live params update over window messaging was not tested/implemented in fiat at all
BEFORE:
updates not applying
https://github.com/user-attachments/assets/4a7b5f4f-fa88-4bd5-b115-80ae83dd4a5d
AFTER:
https://github.com/user-attachments/assets/632d4fce-04a2-45fb-be87-957206fd1689

embed: fix fiat live update params

---

packages/client/wallets/smart-wallet/src/api/CrossmintWalletService.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/eoa.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/passkey.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/service.ts
packages/client/wallets/smart-wallet/src/error/index.ts
packages/client/wallets/smart-wallet/src/index.ts
packages/client/wallets/smart-wallet/src/types/API.ts
packages/client/wallets/smart-wallet/src/types/internal.ts
packages/client/wallets/smart-wallet/src/utils/helpers.ts

This PR defines and uses two new errors:
- AdminMismatchError
- PasskeyMismatchError
As defined in [the errors spec](https://github.com/Paella-Labs/aa-wallet-sdk-docs/pull/6) (with some small improvements)
Locally, using the demo site, I tested each error.

Smart Wallets: Admin & Passkey Mismatch Errors (Resolves WAL-2468 and WAL-2578)

---

packages/client/wallets/smart-wallet/src/services/logging/DatadogProvider.ts

This PR stops us from forwarding `console.error` logs to our DD.
Reproduce the issue via ngrok. Toggle the setting, and confirm that error logs no longer show up.

Smart Wallets: Turn Off DD Error Forwarding (Resolves WAL-2521)

---

packages/client/wallets/smart-wallet/src/api/APIErrorService.ts
packages/client/wallets/smart-wallet/src/error/index.ts
packages/client/wallets/smart-wallet/src/index.ts

This PR contains:
- A resolution for [WAL-2452](https://linear.app/crossmint/issue/WAL-2452/throw-good-error-when-project-is-configured-with-custodial-wallets)
- A proposal for how we should organize errors, namely that:
- All errors should be associated with a string code
- This code can be thrown from our server and processed and re-thrown by our SDK (both of these are similar to how Payments works)
- We should rely on the string error code instead of error subtypes, mostly for the sake of simplicity and DRY
Needs https://github.com/Paella-Labs/crossbit-main/pull/13973 to be landed to throw our new error and resolve the linked issue
TBA

Add error for projects without non-custodial wallets enabled

---

packages/client/wallets/smart-wallet/src/api/APIErrorService.ts
packages/client/wallets/smart-wallet/src/error/index.ts

We had a bug here where the proper error was being selected and logged to the console, but not actually thrown up the call stack. When I was testing this I misread the console output
This PR also includes changes that I accidentally didn't stage for a previous PR, which is to add an SDK code to the error that we throw when a project isn't configured to use non custodial wallets
Tested locally

Fix: `APIErrorService` not actually throwing the error up the call stack

---

apps/wallets/smart-wallet/react/src/app/utils/createAAWallet/createMetamaskWallet.ts
apps/wallets/smart-wallet/react/src/app/utils/createAAWallet/createPasskeyWallet.ts
apps/wallets/smart-wallet/react/src/app/utils/createAAWallet/createViemWallet.ts
apps/wallets/smart-wallet/react/src/app/utils/createAAWallet/createW3AAAWallet.ts
apps/wallets/smart-wallet/react/src/app/utils/getContracts.ts
apps/wallets/smart-wallet/react/src/app/utils/mintApi.ts
crossmint-sdk.code-workspace
packages/client/wallets/smart-wallet/src/index.ts
packages/client/wallets/smart-wallet/src/types/Tokens.ts
packages/client/wallets/smart-wallet/src/types/internal.ts
packages/client/wallets/smart-wallet/src/utils/blockchain.ts
packages/client/wallets/smart-wallet/src/utils/signer.ts
packages/client/wallets/web3auth-adapter/src/index.ts

This PR:
- removes the `SmartWalletChain` export from `@crossmint/client-sdk-smart-wallet`, and replaces it with the chains from the core sdk package, renamed from `EVMChainsIncludingTestnet` to `Chain`.
- renames the chain export from `@crossmint/client-sdk-smart-wallet-web3auth-adapter`, which is already doing what I mention above, from `Blockchain` to `Chain`.
These are breaking changes, but I only want to do a patch version bump, the SDK shipped less than 24 hrs ago and is in EAP mode so I'm comfortable breaking semantic versioning rules.
Updated the Demo to use the new export and TS compiled.

Smart Wallets: Update Chain Export

---

crossmint-sdk.code-workspace
packages/client/wallets/smart-wallet/src/blockchain/wallets/passkey.ts
packages/client/wallets/smart-wallet/src/error/index.ts
packages/client/wallets/smart-wallet/src/index.ts

This PR:
- lays the foundation for catching passkey specific errors
- adds an error for when a passkey prompt is cancelled or times out.
Locally, using the demo site, tested the error both when registering a passkey for a new wallet and signing a user operation.

Smart Wallets: Passkey Prompt Error (Resolves WAL-2464)

---

packages/client/wallets/smart-wallet/src/blockchain/wallets/passkey.ts
packages/client/wallets/smart-wallet/src/error/index.ts
packages/client/wallets/smart-wallet/src/index.ts

We receive a pretty vague error through the SDK when our passkey server fails to verify a registration, either because it took too long, or the signature was invalid.
This PR adds error handling for this case!
Locally reproduced the error, confirming the new improved error is thrown now.

Smart Wallets: Passkey Registration Error (Resolves WAL-2557)

---

packages/client/wallets/smart-wallet/src/blockchain/wallets/passkey.ts
packages/client/wallets/smart-wallet/src/error/index.ts
packages/client/wallets/smart-wallet/src/index.ts

Mystery solved, full investigation here: https://linear.app/crossmint/issue/WAL-2587/mystery-webauthn-error
This PR handles an error that only occurs when a newly registered passkey's public key has a format incompatible with the P256 signature verification that happens onchain. We've only been able to reproduce this with older yubikeys.
Reproduced the error, and made sure the improved error is now thrown.

Smart Wallets: Passkey Incompatible Authenticator Error (Resolves WAL-2587)

---

packages/client/wallets/smart-wallet/src/SmartWalletSDK.ts
packages/client/wallets/smart-wallet/src/api/APIErrorService.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/clientDecorator.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/service.ts
packages/client/wallets/smart-wallet/src/error/index.ts
packages/client/wallets/smart-wallet/src/error/processor.ts
packages/client/wallets/smart-wallet/src/index.ts
packages/client/wallets/smart-wallet/src/utils/signer.ts

When interacting with other libs I often wish they exported their error codes. This PR does just that for the smart wallet SDK.
This PR also:
- Renames `SmartWalletSDKError` => `SmartWalletError`
- Makes some refinements to our error codes
Sanity checked export works as expected + existing CI.

Smart Wallets: Export Error Codes

---

packages/client/wallets/smart-wallet/src/blockchain/chains.ts

Adding two different chains with low gas fees and EIP-7212 support
Some highlights:
- Set the webhook policy to the same as for other SFK projects. That is, 
`https://crossmint-main-staging.azurewebsites.net/api/unstable/wallets/aa/webhookPolicy`
`https://crossmint-main.azurewebsites.net/api/unstable/wallets/aa/webhookPolicy`
- Set the gas sponsoring policy to 500 gwei max on mainnets and 1000 gwei on testnets
Decided not to integrate Ethereum as neither gas is cheap nor has secp256r1 support.
Both chains support the latest v0.7 Entrypoint and v3.1 Kernel
AA mint on Optimism using passkeys https://sepolia-optimism.etherscan.io/tx/0x2e4cf72c81b0936f5dd06cf5a35f0637ade9e49dd9b87acd299b8d83b766b7f0 
And another AA mint on Arbitrum Sepolia …

AA: Add Optimism/Arbitrum mainnet and testnet

---

packages/client/ui/react-ui/src/hooks/index.ts
packages/client/ui/react-ui/src/hooks/useCrossmint.test.tsx
packages/client/ui/react-ui/src/hooks/useCrossmint.tsx
packages/client/ui/react-ui/src/index.ts

another attempt...
tested basic reactability without using a class, calling setJwt rerenders and crosmint.jwt has the new state
tested storing a reference to `crossmint` within a class, updating the jwt from within the class, and seeing that react also gets the new update

feat: useCrossmint + CrossmintProvider

---

apps/wallets/smart-wallet/next/tsconfig.json
apps/wallets/smart-wallet/react/tsconfig.json
packages/client/wallets/smart-wallet/src/blockchain/wallets/account/eoa.ts
packages/client/wallets/smart-wallet/tsconfig.json

Sometimes, we run into issues importing packages that use bigints with modern syntax (ie. `5n`). This PR changes the target in all smart wallet related packages:
- To unify the build target
- To enable use of native bigint syntax
- Even though TS should handle dealing w/ different build targets, I have a hunch this'll help.
I don't see bigint related errors when running the ts compiler anymore
Existing CI should be good here

Smart Wallets: Target ES2020

---

crossmint-sdk.code-workspace

I keep on mixing these up or wasting brain cycles making sure to choose the right one. This PR improves workspace naming for the demos
Before:
After:
N/A

Smart Wallets: Improve Demo Workspace Names

---

packages/client/base/src/services/api/BaseCrossmintService.ts
packages/client/base/src/utils/SDKLogger.ts

Two changes:
- Ensure we include the operation name in these logs
- Change the endpoint logged in FETCH_CROSSMINT_API to not include query parameters for better aggregation
Ran though demo locally and ensured the above work

Improve `logPerformance` metadata fields

---

packages/client/ui/react-ui/jest.config.js
packages/client/ui/react-ui/package.json
packages/client/ui/react-ui/src/components/CrossmintCollectionView.test.tsx
packages/client/ui/react-ui/src/components/CrossmintNFTDetail.test.tsx
packages/client/ui/react-ui/src/components/embed/CrossmintPaymentElement.test.tsx
packages/client/ui/react-ui/src/components/embed/EmbeddedCheckoutIFrame.tsx
packages/client/ui/react-ui/src/components/embed/crypto/CryptoEmbeddedCheckoutIFrame.tsx
packages/client/ui/react-ui/src/components/embed/fiat/FiatEmbeddedCheckout.tsx
packages/client/ui/react-ui/src/components/embed/fiat/FiatEmbeddedCheckoutIFrame.tsx
packages/client/ui/react-ui/src/components/hosted/CrossmintPayButton.test.tsx
packages/client/ui/react-ui/src/hooks/useCrossmint.test.tsx
packages/client/ui/react-ui/vitest.config.ts

Jest (or at least how we've configured it) often struggles to build things to test, and when it fails does not provide useful error messages. This has caused me to get waste hours multiple times, bit the bullet here and converted the package to use vitest, which is much better and provides error messages that let you actually fix any build issues that come up!
Newer packages all use vitest, this change pushes the repo further in that direction.
This PR also converts a few imports that look like this `@/x/y` into `../../x/y` to fix some build issues (that vitest reported, maybe there's some config we could set to enable, but less drama to just have the regular imports instead.)
Existing tests run and pass.

React UI Lib: Convert Testing Suite To Vitest

---

packages/client/wallets/smart-wallet/src/blockchain/chains.ts
packages/client/wallets/smart-wallet/src/blockchain/rpc.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/paymaster.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/service.ts
packages/client/wallets/smart-wallet/src/utils/constants.ts

The process of sending a user op requires a few bundler calls:
- One to fetch the gas price,
- Another to actually send the signed user op,
- Finally, we poll for the receipt
This PR switches us over to using the [Pimlico](https://www.pimlico.io/) bundler directly, instead of proxying them through ZeroDev. The primary benefit here is that, at least locally for me, this shaves off 400 - 500 ms of latency from each call mentioned above. This shaves ~2 seconds from each transaction flow, which is a huge UX improvement.
Went through the Minting + Smart Wallet Demo flow.

Smart Wallets: Reduce Bundler Latency (Resolves WAL-2749)

---

packages/client/wallets/smart-wallet/custom-plugin.mjs

problem:
- typedoc generates markdown style links that lack the `./` preceding them
- this confuses mintlify and the links open in a new tab.
solution:
this adds code to the custom plugin file for typedoc that searches for all occurrences of `](` not followed by http or `../` (to avoid breaking correct external links and relative path) and replaces it with `](./`
- tested locally by running `npx typedoc` and examining the generated docs directory
- previously 304 occurrences matching regex: `\]\((?!http|\.{2}\/)` and now zero (when adding negative look ahead for `./` also

docs: add line to fix links during generation

---

packages/client/wallets/smart-wallet/src/blockchain/wallets/SendTransactionService.ts

Just noticed this mistake after merging the main PR
We removed this field, e.message is correct because it contains the message from the viem revert error
N/A

AA: Fix incorrect jsdoc

---

.changeset/three-pots-rescue.md
packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx

This PR fixes an issue where, in the event of an error in `SmartWalletSdk.getOrCreateWallet`, we'd call it again in repeat. @jmderby, who'll be reviewing this PR, and I are in the same room and we've shared more context in person.
On the Smart Wallet + auth  Demo:
- Happy path, login and mint flow.
- Confirmed we're no longer repeating requests in the event of an error.
- Confirmed that the `getOrCreateWallet` function we expose from `useWallet` can be used to successfully recover from the error state.

Smart Wallets: Fix Error Loop Issue

---

.changeset/good-pumpkins-laugh.md
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
packages/client/wallets/smart-wallet/src/index.ts

We temporarily only had staging chains enabled for these providers, this PR updates the SDK to enable the use of all Smart Wallet supported chains.
Sanity checked that the auth + smart wallet demo flow still works.
This PR patches both `@crossmint/client-sdk-smart-wallet` and `@crossmint/client-sdk-react-ui`

Smart Wallets + Auth: Enable All Smart Wallet Chains For `CrossmintAuthProvider` & `CrossmintWalletProvider`

---

.changeset/metal-pumpkins-taste.md
packages/client/wallets/smart-wallet/src/SmartWalletSDK.ts
packages/client/wallets/smart-wallet/src/blockchain/chains.ts

This PR adds chain <> env validation, so if a dev provides a staging API key and a mainnet chain (or vice versa), they'll get an error message that looks like this:
Locally, within the smart wallet SDK playground:
- Confirmed the error case works as expected, as pictured above, for both staging & production keys.
- Sanity checked that the happy path still works.
patch `@crossmint/client-sdk-smart-wallet`

Smart Wallet: Chain <> Env Validation

---

.changeset/sweet-poems-decide.md
packages/client/ui/react-ui/src/components/auth/AuthModal.tsx

Fixed bug with uri that the iframe calls was improperly formatted.
Development and staging still work and bug is now exterminated 
**@crossmint/client-sdk-react-ui**

Auth modal: Fixed uri string bug

---

.changeset/tricky-lobsters-exercise.md
packages/client/ui/react-ui/src/components/auth/AuthModal.tsx
packages/client/ui/react-ui/src/consts/version.ts

Padding has been added for auth view in crossbit-main and it breaks otp in mobile
Open auth modal in next demo

Removes horizontal padding in auth iframe

---

.changeset/smooth-mirrors-protect.md
packages/client/ui/react-ui/src/hooks/useCrossmint.tsx
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.test.tsx
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.test.tsx
packages/client/ui/react-ui/src/utils/constants.ts
packages/client/ui/react-ui/src/utils/index.ts
packages/client/ui/react-ui/src/utils/jwt.ts

Right now, within the `CrossmintProvider` component, we read from cookies for Crossmint Auth sessions to populate the initial JWT. Since Next.js generates a static page when possible, the first render, which is that static page, would not have a JWT value. The subsequent hydration would read in the cookies, and cause an error because the static page and first client render would be different, which is not allowed.
This PR moves reading the cookie to a `useEffect` that only happens once on render client side, fixing the hydration error.
There's pretty solid unit test coverage over `CrossmintProvider`, `CrossmintAuthProvider`, which should continue to pass here.
Locally, I ran through the demo flow and confirmed everything worked as expected, w/ no hydration issues.

Crossmint Provider: Hydration Fix (Resolves WAL-2880)

---

.changeset/silver-swans-brush.md
packages/client/ui/react-ui/src/hooks/useCrossmint.tsx

atm we let developers set jwt from the props, or via setJwt, but there's no clear way they can co-exist. For example, what if a developer uses the jwt prop, but then calls setJwt? Do the jwt prop and actual jwt differ in value? etc.
This PR removes the `jwt` prop. I considered removing `setJwt` instead, but that's not possible atm since `CrossmintAuthProvider` relies on it.
Existing unit tests.
Locally, I went through the auth + smart wallet demo flow just in case XD.
patch `@crossmint/client-sdk-react-ui`

Crossmint Provider: Drop `jwt` prop (Resolves WAL-2884)

---

.changeset/fast-suns-accept.md
packages/client/wallets/smart-wallet/src/index.ts
packages/client/wallets/smart-wallet/src/types/internal.ts
packages/client/wallets/smart-wallet/src/types/params.ts

This PR renames `EOASigner` to `ExternalSigner` for a couple reasons:
- It's not accurate, `1193Provider` a valid `EOASigner` is a generic interface for wallets and can even represent AA wallets.
- It's confusing, if I wanted to use a privy, dynamic, or web3auth signer `EOASigner` is not obvious, but `ExternalSigner` is!
Ofc open to further naming improvements.
N/A
patch `@crossmint/client-sdk-smart-wallet` (XD will respect semver after the public announcement)

Smart Wallets: Rename `EOASigner` => `ExternalSigner`

---

.changeset/afraid-items-fly.md
packages/client/base/src/error/index.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/EVMSmartWallet.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/SendTransactionService.test.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/SendTransactionService.ts
packages/client/wallets/smart-wallet/src/blockchain/wallets/service.ts
packages/client/wallets/smart-wallet/src/index.ts
packages/client/wallets/smart-wallet/src/types/token.ts

This PR does two things:
- Re-uses `executeContract` within `transferToken` for improved and consistent error handling within our transaction helper functions on `EVMSmartWallet`.
- Fixes an error within the `executeContract` function where we simulate the transaction with the wrong address.
I've annotated the PR with more detail where appropriate.
Initially I found the issue when attempting to transfer an NFT I had just minted, to test these changes locally, I made sure the mint flow, along with transferring the NFT worked within the wallets playground. I also sanity checked the Auth + Smart Wallet demo.
I also added a unit test coverage within `SendTransactionService` making sure the right address gets used.
patch `@crossmint/client-sdk-base`
patch `@crossmint/client-sdk-smart-wallet`

Smart Wallets: Re-use `executeContract` Within `transferToken` + Fix `executeTransaction` Simulation Bug (Resolves WAL-2919)

---

.husky/pre-commit
biome.json
package.json
pnpm-lock.yaml

This PR deletes our pre-commit hooks, I've noticed it causes trouble (not working w/ different node installations, weird failure states myself and other eng have gotten into). We already run the lint & format check in CI, plus have the workspace setup to format on save, which should be more than enough.
I've already been operating w/o the pre-commit hook locally for the past few months since I started working on the SDK and haven't had any issues.
n/a
n/a

SDK Internal DX: Prune Pre-Commit Hook & Unused Dev Deps

---

.changeset/fifty-tomatoes-approve.md
packages/client/ui/react-ui/src/hooks/useRefreshToken.ts

Currently, React Strict Mode triggers hooks twice, which ends up calling /refresh twice, and the second time fails logging users out. This forces that it only runs once at a time, even in dev mode.
Run smart wallets demo app and check in networks tab in inspector that /refresh is only triggered once.
@crossmint/client-sdk-react-ui patch

Auth: Makes sure refreshAuthMaterial is only ran once at a time

---

.changeset/brown-rice-push.md
.changeset/fifty-tomatoes-approve.md
.changeset/moody-pigs-sneeze.md
apps/payments/create-react-app/CHANGELOG.md
apps/payments/create-react-app/package.json
apps/payments/nextjs/CHANGELOG.md
apps/payments/nextjs/package.json
apps/wallets/smart-wallet/next/CHANGELOG.md
apps/wallets/smart-wallet/next/package.json
packages/client/auth-core/src/services/CrossmintAuthService.ts
packages/client/ui/react-ui/CHANGELOG.md
packages/client/ui/react-ui/package.json
packages/client/ui/react-ui/src/components/auth/AuthModal.tsx
packages/client/ui/react-ui/src/hooks/useRefreshToken.ts
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx

Makes SDK listen to initial one-time refresh token to then fetch all auth material.
Also removes unused popup/iframe events. Please test locally to double check it's working.
Delete cookies => Log in with both OTP and OAuth
@crossmint/client-sdk-react-ui v1.5.0

Auth: Implements one time use refresh token to fetch auth material

---

.changeset/stale-eyes-think.md
apps/payments/create-react-app/package.json
apps/wallets/smart-wallet/react/package.json
packages/client/auth-core/package.json
packages/client/ui/react-ui/package.json
packages/client/ui/react-ui/src/components/auth/AuthModal.tsx
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
packages/client/wallets/smart-wallet/package.json

Due to how `iframeWindow` was being created and the fact that `React.StrictMode` runs all hooks twice, we were listening to the post message events on the iframe twice, and therefore calling `/refresh` twice with the same refresh secret which would sometime throw an error
Running the demo app in dev mode (`React.StrictMode = true`) and authenticating via email will now make a single call to `/refresh`
`@crossmint/client-sdk-react-ui`: patch

Cleans up how refresh tokens are received to avoid multiple refreshes

---

.changeset/empty-bees-occur.md

We deleted the library before it publishes so don't need the change set.
None
None

removes server-sdk-auth changeset

---

.changeset/long-bugs-remain.md
packages/client/ui/react-ui/src/components/auth/AuthModal.tsx
packages/client/ui/react-ui/src/components/auth/PasskeyPrompt.tsx
packages/client/ui/react-ui/src/components/common/PoweredByCrossmint.tsx

Unblocks #788 and we [shouldn't be using dynamic classes](https://tailwindcss.com/docs/content-configuration#:~:text=the%20corresponding%20CSS%3A-,Don%E2%80%99t%20construct%20class%20names%20dynamically,-%3Cdiv%20class) for tailwind anyway: 
Ran next demo with and without appearance object
`@crossmint/client-sdk-react-ui` patch

Removes dynamic tailwind classes as they break tree shaking build

---

.changeset/funny-countries-shave.md
packages/client/ui/react-ui/src/utils/authCookies.ts

We decided `crossmint-jwt` is clearer than `crossmint-session` as the refresh token would count as the session. The `server-sdk` will only work with the new name and with versions of `react-ui` that include this change.
This will not log out users as the refresh token doesn't change and it will use that on page load to fetch a new jwt and set the new cookie. But this also doesn't delete the old `crossmint-session` cookie. I think this is okay as we're not in Prod yet and it's only a few projects testing, this way, we avoid having to follow a deprecation process.
Ran smarter wallets demo
`@crossmint/client-sdk-react-ui`: patch

Changes jwt cookie name to crossmint-jwt

---

.changeset/silent-trains-explode.md
packages/client/ui/react-ui/tsup.config.ts

Otherwise, the twind instantiation in `index.ts` doesn't occur as we're only importing the specific named imports and it doesn't go through `index.ts`
Loaded the smarter wallet demo and saw that the passkey prompt now shows up

Adds entrypoint to react-ui to force loading twind

---

packages/client/base/src/types/embed/v3/events/incoming.ts
packages/client/base/src/types/embed/v3/events/outgoing.ts
packages/client/ui/react-ui/package.json
packages/client/ui/react-ui/src/components/embed/v3/crypto/CryptoWalletConnectionHandler.tsx
packages/client/ui/react-ui/src/components/embed/v3/crypto/utils/handleEvmTransaction.ts
packages/client/ui/react-ui/src/components/embed/v3/crypto/utils/handleSendTransaction.ts
packages/client/ui/react-ui/src/components/embed/v3/crypto/utils/handleSolanaTransaction.ts
pnpm-lock.yaml

sending crypto txs on sol and evm
tested both evm and sol
evm switching newtwork + sending working fine
sol sending is working fine, added a todo to work on network swtiching (its more complicated)
did e2e

embed v3: crypto tx sending

---

packages/client/base/src/services/embed/v3/crossmintEmbeddedCheckoutV3Service.ts
packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx

Sending SDK info to the iframe

embedded-v3: send sdk info in iframe

---

apps/payments/nextjs/components/embed-v3/EmbeddedCheckoutV3ClientProviders.tsx
apps/payments/nextjs/components/embed-v3/EmbeddedCheckoutV3Content.tsx
apps/payments/nextjs/pages/embedded-checkout/v3.tsx
packages/client/base/src/types/embed/v3/events/incoming.ts
packages/client/ui/react-ui/src/components/embed/v3/EmbeddedCheckoutV3IFrame.tsx
packages/client/ui/react-ui/src/hooks/index.ts
packages/client/ui/react-ui/src/hooks/useCrossmintCheckout.tsx
packages/client/ui/react-ui/src/utils/createCrossmintApiClient.ts

CrossmintChechkoutProvider and useCrossmintCheckout, according to [doc](https://docs.google.com/document/d/1y602C9MwV8HZi9aLTDR0KANOcvnTZEP0tvqmE_OqXDA/edit?tab=t.0)
the one difference from the doc is i didnt do the polling in the sdk feature yet, will do it soon
whenever order gets created/update, its sent through the window to the sdk

embed: useCrossmintCheckout

---

.changeset/little-meals-move.md
packages/client/window/src/EventEmitter.ts
packages/client/window/src/handshake/Child.ts
packages/client/window/src/windows/Child.ts

We need to allow many origins to avoid a security flag explained [here](https://linear.app/crossmint/issue/WAL-3075/security-issue-replace-wildcard-in-postmessage-with-specific-origin)
✅ `*`: Sign in any domain
✅ `whitelistedOrigins`: Sign in a whitelisted origin
❌ `whitelistedOrigins`: Sign in an origin that isn't whitelisted:
https://www.loom.com/share/34f4ed0180e14d8b8fd172b90235a83c
Window

Window: allow many origins

---

.changeset/neat-dots-vanish.md
packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.tsx

With [this PR](https://github.com/Paella-Labs/crossbit-main/pull/15388), we need all Auth requests to send the API key in the header instead of as a query parameter. We were missing this oauth fetch.
Opened smarter wallet and saw in the console the api key is now sent in the header.

Also send api key in header in oauth fetch to support backend change

---

.changeset/clean-crews-greet.md
packages/client/ui/react-ui/package.json
packages/client/ui/react-ui/src/hooks/useCrossmint.tsx
packages/client/ui/react-ui/src/index.ts
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
packages/client/ui/react-ui/src/providers/TwindProvider.tsx
packages/client/ui/react-ui/tsup.config.ts

This PR adds tree shaking capabilities back to the react-ui package
The solution around our twind issue was to add a TwindProvider that runs `install` inside a useEffect on mount.
Tested build and styles worked as expected.

Tree shaking: react-ui fix

---

packages/client/ui/react-ui/package.json

Development was encountering a out of heap memory. This applies the same max amount as build does.
development doesnt crash
i don't think we need a release for this change

React ui: increased development memory

---

.changeset/light-balloons-promise.md
packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts

this is really strange, havnt seen this before but for some reason the `|` in ts isnt working as expected, and still allowing both email AND walletAddress
this should force it to be only one or the other
before:
now:
errors
passes with 1 or the other

embed: fix weird recipient ts behavior

---

.changeset/ten-mayflies-unite.md
packages/client/auth/package.json
packages/client/auth/src/CrossmintAuthClient.test.ts
packages/client/auth/src/CrossmintAuthClient.ts

Strong assurance that refresh won't be called twice
I created a test
client-auth: patch

Makes it impossible to call refresh twice in the client

---

.changeset/funny-hornets-behave.md
packages/client/auth/src/CrossmintAuthClient.ts

We accidentally deprecated some sdk code before backend changes landed. Just needed to revert that change.
tested all auth flows, work as expected
@crossmint/client-sdk-auth:patch

Auth OTP: fixed bug with api request

---

.changeset/gentle-planes-search.md
apps/payments/nextjs/pages/payment-element/eth.tsx
apps/payments/nextjs/pages/payment-element/fiat.tsx
apps/payments/nextjs/pages/payment-element/sol.tsx
packages/client/ui/react-ui/src/components/embed/CrossmintPaymentElement.test.tsx
packages/client/ui/react-ui/src/components/embed/index.tsx

Embedded v3 is the default and recommended version. Flag the old component as deprecated.

embedded-v2: flag component as deprecated

---

.changeset/wild-news-cheat.md
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx

Fixed issue with React not re-rendering upon jwt invalidation and new one being set
1. repro bug
2. fix and remove ability to repro bug

Fix: stale JWT re-render bug

---

.changeset/bright-foxes-hope.md
packages/client/ui/react-ui/src/components/auth/AuthForm.tsx
packages/client/ui/react-ui/src/components/auth/AuthFormDialog.tsx
packages/client/ui/react-ui/src/components/auth/methods/email/EmailOTPInput.tsx
packages/client/ui/react-ui/src/components/auth/methods/email/EmailSignIn.tsx
packages/client/ui/react-ui/src/components/auth/methods/farcaster/FarcasterSignIn.tsx
packages/client/ui/react-ui/src/components/auth/methods/google/ContinueWithGoogle.tsx
packages/client/ui/react-ui/src/components/auth/methods/google/GoogleSignIn.tsx
packages/client/ui/react-ui/src/components/auth/methods/twitter/TwitterSignIn.tsx
packages/client/ui/react-ui/src/components/common/CountdownButton.tsx
packages/client/ui/react-ui/src/components/common/Dialog.tsx
packages/client/ui/react-ui/src/components/common/SecuredByCrossmint.tsx
packages/client/ui/react-ui/src/hooks/useOAuthWindowListener.ts
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.tsx
packages/client/ui/react-ui/src/twind.config.ts

This pr contains all of the changes from our design UI
- new feel 
- new prop exposed called `termsOfServiceText` that can pass a string or reactnode with links nested
- new prop exposed: `authModalTitle` that allows the title of the modal to be changed
- email input shows a "Continue" button that logs you in with google if you use a `gmail.com` domain
- plus, if your already authenticated in the same browser, it'll auto sign in
- built and tested with yalc
- customized appearance object styles
- exhausted a lot of manual testing 

UI design overhaul

---

.changeset/eleven-sloths-carry.md
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.test.tsx
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.test.tsx
packages/client/ui/react-ui/src/providers/auth/AuthFormProvider.tsx

Changes prevent /start endpoint to be called unless they are logged out
Tested and /start calls weren't made when user was logged in or logging in. 

Auth: Prevent /start calls when logged in

---

.changeset/clean-keys-wash.md
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx
packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx

Adds a callback for successful logins called onLoginSuccess
works for both pre-wallet users and logged in users

Auth: add onLoginSuccess callback

---

.changeset/lucky-trains-rush.md
packages/server/src/auth/CrossmintAuthServer.ts
packages/server/src/auth/utils/jwt.ts

allow local jwks, to skip remote fetch

auth: allow local jwks

---

.changeset/late-moons-study.md
packages/client/ui/react-ui/src/icons/google.tsx

the initial render of the embedded auth form creates a massively jarring experience 
closes issue: https://linear.app/crossmint/issue/WAL-3702/visual-bug-initial-rendering-icon-size-embeddedauthform
built pckg/app and tested, icon was regular size on initial render

EmbeddedAuthForm: fix Google icon size on initial page load

---

.changeset/tender-cheetahs-watch.md
package.json
packages/client/window/package.json
pnpm-lock.yaml

Updating the `nanoid` dependency to fix the [CVE-2024-55565](https://nvd.nist.gov/vuln/detail/cve-2024-55565) security vulnerability.
1. Skim the 'Files Changed' tab.
2. Don't shy away and check the CICD run.
3. If you feel adventurous, check out this branch and run the tests locally.
@crossmint/client-sdk-window

update: nanoid

---

apps/wallets/smart-wallet/react/package.json
pnpm-lock.yaml

The package inside `apps/wallets/smart-wallet/react` wasn't building.
**Root cause**
The abitype package (which is a dependency of viem) was looking for @babel/runtime@7.24.7, specifically the wrapRegExp.js file.
However, the project had @babel/runtime@7.26.0 and @babel/runtime@7.9.0 installed, but not version 7.24.7.
This version mismatch caused the build to fail because it couldn't find the specific file in the expected location.
**Solution**:
Installed specific version of @babel/runtime that was being referenced using:
`pnpm install @babel/runtime@7.24.7 --save-exact`
Can build with `cd apps/wallets/smart-wallet/react &&npm run build`

React Smart Wallet App: fix build issue

---

.changeset/smooth-chairs-wash.md
packages/client/ui/react-ui/package.json
packages/client/ui/react-ui/src/hooks/index.ts
packages/client/ui/react-ui/src/hooks/useWalletCache.ts
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.test.tsx
packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.test.tsx
packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
packages/client/wallets/smart-wallet/src/evm/smartWalletClient.ts
packages/client/wallets/smart-wallet/src/index.ts
packages/client/wallets/smart-wallet/src/sdk.ts
packages/client/wallets/smart-wallet/src/smartWalletService.ts
pnpm-lock.yaml

Fixes `@crossmint/client-sdk-react-ui` by storing the wallet state in LocalStorage. Also uses newly added wallet action callbacks from `@crossmint/client-sdk-smart-wallet` to render passkey prompts.
Passkey callbacks and wallet persistence were removed from `@crossmint/client-sdk-smart-wallet` in #966 to reduce its scope. Removing that from the TS SDK was intentional, but this broke some of the functionality in React SDK.
This PR ports that functionality into the React SDK. This makes the passkey prompts being rendered again, and persists the wallet state across browser sessions.
* CI passes
* Lack of breaking changes
* Using React SDK should persist the wallet state and render the prompt
* Can test by running the `apps/wallets/smart-wallet/next` playground app
``` …
```

Smart Wallet React SDK: fix wallet persistence & passkey prompts

---

.changeset/shaggy-garlics-decide.md
packages/wallets/src/api/client.ts
packages/wallets/src/evm/utils.ts
packages/wallets/src/services/wallet-factory.ts
packages/wallets/src/solana/wallet.ts

PR fixes the following: 
- passing the adminSigner.name or fallback to existing
- nfts method - the pagination params order was incorrect
- fixes nfts method for solana
- renamed `createWallet` to `getOrCreateWalletInternal`
- only call onWalletCreationStart callback when actually creating a wallet
wallets-sdk works as expected without errors regarding signing, wallet.nfts(...), or wallet creation passkey prompts

Wallets SDK: Small Fixes

---

.changeset/shy-trains-leave.md
packages/wallets/package.json

Fix our build script to run the code generation stuff rather than postinstall (which gets triggered in ANY subsequent projects using the sdk)
Error from attempting to run `pnpm i` in our smarter wallets demo repo
ensure original intent of generating codegen still works and that this doesn't cause side effects

Wallets SDK: fix code gen script

---

packages/wallets/README.md

Fix `MCP Wallets` → `MPC Wallets` typo in README
* CI
* No more typos

docs: fix typo in Wallets SDK

---

.changeset/big-bulldogs-prove.md
packages/client/ui/react-ui/src/components/common/Dialog.tsx
packages/client/ui/react-ui/src/twind.config.ts

Disabled preflight in CSS to prevent style conflicts with client apps. Updated dialog transform property to use direct value instead of shorthand to avoid any ui bugs/interference.
This should've probably already been disabled but we can at least catch it now to minimize any further disruption in client apps using the react sdk. 
Changes:
- Set disablePreflight: true
- Fixed side-effect in dialog component just using the translate(-50%, -50%)  
- tested against a completely separate app built using yalc and styling override was no longer happening and all styles /ui elements worked and looked as expected (from the sdk)
- tested on Safari, google chrome, and ofc in smart wallet demo

Tailwind styles: Disable preflight fix style override

---

.changeset/weak-lemons-roll.md
packages/client/ui/react-ui/src/components/embed/v3/crypto/CryptoWalletConnectionHandler.tsx

If the user's wallet is on a chain we don't support (this should only happen for EVM):
- Switch to the default chain
- If that fails, return an error explaining user must switch to a supported chain
pretty straight forward

pay w crypto: switch to default chain if not supported

---

.changeset/strong-berries-tease.md
packages/client/base/src/error/index.ts

Exports `CrossmintErrors` in `@crossmint/client-sdk-base` to fix the `crossbit-main` build.
Also exports `CrossmintSDKError, PaymentErrors, SmartWalletErrorCode, WalletErrorCode` that were also previously exported to keep backwards compatibility.
Those were moved to `@crossmint/client-sdk-base` in a larger refactor, but haven't been reexported.
* CI
* exports
```
"@crossmint/client-sdk-base": patch
```

Fix `CrossmintErrors` not exposed

---

.changeset/tiny-donuts-arrive.md
packages/wallets/src/solana/services/approvals-service.test.ts
packages/wallets/src/solana/services/approvals-service.ts

Fixed our signing mechanism for signing solana txns.
To provide some context here, according to Claude this is whats happening
> This is a security protection - Phantom (and other Solana wallets) deliberately prevent you from using the signMessage method to sign transaction data. This prevents potential security exploits where users think they're signing a message but are actually signing a transaction.
Therefore, from my understanding the following was necessary:
1. the server sends a serialized transaction message from the transaction
2. then, we need to convert that serialized transaction message back into a transaction and use the signTransaction function from our wallet provider (dynamic in our case i'm not 100 percent confident this will work with other providers but it should based …

Solana sendTransaction: Fix signing for keypair

---

.changeset/angry-carpets-rest.md
.changeset/dry-hats-admire.md
packages/client/react-base/src/hooks/useCrossmint.tsx
packages/common/base/src/apiClient/CrossmintApiClient.ts
packages/common/base/src/types/Crossmint.ts

We verify requests from mobile with this header, now we'll support it in our base sdks and api client.
Tested with expo app
react-base: minor
common-base: minor

SDK: Send App id header in all requests from mobile

---

.changeset/few-mice-care.md
apps/wallets/smart-wallet/next/src/app/wallet/page.tsx
packages/wallets/src/api/client.ts
packages/wallets/src/evm/index.ts
packages/wallets/src/evm/types/signers.ts
packages/wallets/src/evm/types/wallet.ts
packages/wallets/src/evm/utils.ts
packages/wallets/src/evm/wallet.ts
packages/wallets/src/index.ts
packages/wallets/src/services/types.ts
packages/wallets/src/services/wallet-factory.test.ts
packages/wallets/src/services/wallet-factory.ts
packages/wallets/src/solana/index.ts
packages/wallets/src/solana/services/delegated-signers-service.ts
packages/wallets/src/solana/types/wallet.ts
packages/wallets/src/solana/wallet.ts

• Standardizes return value from getOrCreateWallet method, this ensures the return type matches the actual returned wallet instance
• Adds `get` prefix to all getter methods for consistency
• Adds getDelegatedSigners method to solana-smart-wallet
additional context: 
what we currently **have**: (similar applies to evm)
what we **want**:
Added additional automated test cases for evm and existing sol, manually tested wallets object, and type remain the same but return value is now correct.

Wallets SDK: Standardize wallet return type

---

packages/wallets/src/solana/services/approvals-service.test.ts
packages/wallets/src/solana/services/approvals-service.ts
packages/wallets/src/solana/services/transaction-service.test.ts
packages/wallets/src/solana/services/transactions-service.ts

This was popping up in the backpack wallet, the transaction was tampered with in the browser (maybe due to lacking a proper blockhash or signer) and the signature it returned was not the one we expected, which made the transaction fail
Tested by using it in the SSW quickstart, tested backwards compatibility with phantom
Wallets SDK

SSW: fix signature error in some browser wallets

---

.changeset/giant-hats-appear.md
packages/client/wallets/smart-wallet/src/evm/rpc.ts
packages/client/wallets/smart-wallet/src/evm/wallet.ts
packages/client/wallets/smart-wallet/src/smartWalletService.ts

We have some RPCs hardcoded we're treating as public that are remnants of an old architecture. Now that everything is routed through our APIs, the remaining places we do use public PRCs:
- To implement a `viem` interface and support `getNonce`, which calls a smart contract.
- Exposed as `wallet.client.public` from our `EVMSmartWallet` object
Expect little enough usage for default public RPCs from viem.
This is also what we do in our latest package `@crossmint/wallets-sdk`
Didn't test because this PR only:
- deletes unused code
- changes the inputs to `createPublicClient` from our own RPCs to default public RPCs from `viem`. I copied the code populate `createPublicClient` with default RPCs from `@crossmint/wallets-sdk`.
patch `client-sdk-smart-wallet`

Use Public RPCs for `client-sdk-smart-wallet`

---

.changeset/late-news-guess.md
.changeset/tasty-turtles-count.md
packages/client/ui/react-native/src/index.ts
packages/client/ui/react-native/src/providers/CrossmintAuthProvider.tsx
packages/client/ui/react-native/src/providers/index.ts
packages/client/wallets/web3auth-adapter/src/networks.ts

Mixed in a couple of fixes:
- export new types from wallet-sdk in react native
- fixed exporting CrossmintAuthProvider
- Move away from non-functioning rpcs in web3auth-adapter
Tested with expo
web3auth-adapter: patch

Bugs: Exports types from react native + fixes rpcs in web3auth

---

.changeset/metal-crabs-drop.md
packages/common/auth/src/types/user.ts

Since we now expose the twitter username in oauth login method, we needed to update the types.
na
@crossmint/common-sdk-auth

Common sdk auth: Updated twitter metadata type

---

.changeset/selfish-forks-sing.md
packages/client/signers/src/communications/schemas.ts

This PR drops `deviceId` from iframe payloads, since it's now managed internally.
n/a
patch `@crossmint/client-signers` (patch only since we haven't released)

NCS: Remove External `deviceId` from Iframe Payloads

---

.changeset/two-ligers-shake.md
packages/client/signers/src/communications/schemas.ts

We support sending an error in the response.
Also, we allow the create signer response to already contain the address of the signer, not needing to send the OTP and so on.
Will integrate now in the demo

NCS: support non-happy-path responses on events

---

.changeset/warm-spiders-live.md
packages/client/signers/src/communications/events.ts
packages/client/signers/src/communications/schemas.ts

Just adding a generic sign event that will eventually replace chain-specific signMessage and signTransaction logic 
Nothing to be tested

NCS: add sign event

---

.changeset/wet-zebras-peel.md
packages/client/rn-window/src/rn-webview/RNWebView.tsx

We were creating a global event handler for every window handler, but we only need a single global handler.
will test with recovery key iframe once deployed
rn-window: patch

RN: fixes creating multiple same handlers

---

.changeset/wet-zebras-peel.md
packages/client/rn-window/src/rn-webview/RNWebView.tsx
packages/client/rn-window/src/transport/RNWebViewTransport.ts

We were creating a global event handler for every window handler, but we only need a single global handler.
will test with recovery key iframe once deployed
rn-window: patch

RN: fixes creating multiple same handlers #1085

---

.changeset/chilled-weeks-occur.md
packages/client/signers/src/communications/events.ts
packages/client/signers/src/communications/schemas.ts
packages/client/ui/react-native/src/providers/CrossmintRecoveryKeyProvider.tsx
packages/client/ui/react-ui/src/providers/signers/CrossmintSignerProvider.tsx

These events are being deprecated, as they need the Solana specific logic on the iframe side which increases the static bundle size and increases the attack surface. We're moving to a minimal signing logic implementation on the iframe and moving all the serialization specific logic to the SDK instead!
Tested in the live application https://simple-ncs-demo.vercel.app/

NCS: use raw Ed25519 signing for NCSs

---

.changeset/silent-ducks-occur.md
packages/client/signers/src/communications/index.ts
packages/client/signers/src/communications/schemas.ts
packages/client/ui/react-native/src/providers/CrossmintRecoveryKeyProvider.tsx

Just adding a new encoding that we will use for EVM

NCS: add hex encoding

---

.changeset/friendly-chairs-share.md
packages/client/ui/react-ui/src/hooks/useSignerInvisibleIFrame.ts
packages/client/ui/react-ui/src/providers/signers/CrossmintSignerProvider.tsx

For certain API calls we don't have an API key that we can use to infer the environment, so we need to pass it somehow. Here we add a query param for that

NCS: detect iframe environment automatically [WAL-4579]

---

biome.json

The linter was useless because it would complain about files we don't care about
Linter stopped throwing unnecessary errors
None

Lint: ignore .turbo and .d.ts files in biome

---

.changeset/little-lamps-add.md
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.test.tsx
packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx
packages/client/ui/react-ui/src/providers/dynamic/DynamicWalletProvider.tsx

When automatically creating a wallet for BYOA, state relating to Dynamic (which isn't used during BYOA) was being set to false by default `sdkHasLoaded`. Added more state to account for whether the dynamic provider is being used in the first place. 
Auto wallet creation works for both Crossmint auth and BYOA.

React Wallet Provider: BYOA auto wallet create bug

---

.changeset/lucky-weeks-melt.md
.changeset/seven-owls-play.md
.changeset/two-eyes-clap.md
apps/wallets/quickstart-devkit/components/permissions.tsx
packages/client/react-base/src/types/wallet.ts
packages/client/ui/react-ui/src/types/wallet.ts
packages/wallets/src/index.ts
packages/wallets/src/wallets/types.ts
packages/wallets/src/wallets/wallet.ts

Renamed permission methods to delegate signers
build passes and method names are updated.

Wallets sdk: Rename permissions to delegateSigners

---

.changeset/empty-keys-try.md
packages/wallets/src/utils/signer-validation.ts
packages/wallets/src/wallets/wallet-factory.ts

Fix issue with `validateWalletConfig` not working for passkey signer types
passkey signer validation works.

Wallets sdk: Fix passkey signer validation

---

.changeset/wicked-trees-fail.md
packages/client/ui/react-ui/src/components/auth/PasskeyPrompt.tsx
packages/client/ui/react-ui/src/providers/CrossmintWalletProvider.tsx

Fix verbiage of passkey prompt and only show it when the signer type is set to `passkey` 
prompt verbiage now says "Use your wallet" instead of "First Time Using Your Wallet". also only shows when using passkey signer type.

Wallets sdk: Fix passkey prompt

---

.changeset/seven-kings-sleep.md
packages/wallets/src/utils/signer-validation.ts

Our signer deep object comparison wasn't accounting for when an object wasn't deep/nested.
Error no longer fires, other signers still work.

Fix issue with signer validation deep obj comparison

---

.changeset/poor-forks-kick.md
packages/wallets/src/wallets/wallet.ts

As title states;
errors pass through as expected

Wallets sdk: Surface actual error message instead of 'true'

---

.changeset/grumpy-hats-joke.md
packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx

Forgot to pass createOnLogin props through our react native wallet provider.
test
@crossmint/client-sdk-react-native-ui

React Native: pass createOnLogin through

---

.changeset/fifty-books-impress.md
.changeset/spotty-brooms-ring.md
packages/common/base/src/apiClient/CrossmintApiClient.ts
packages/wallets/src/signers/email/email.ts

A rather critical bug has been found and fixed. 
**issue 1:** 
jwt value wasn't using a single source of truth and incorrect value was being used even though jwt was being set on crossmint instance.
**issue 2:** 
email signer error being thrown about email not being set even though it was being set in wallet instance. 
Tested setting jwt in `createCrossmint` instance and setting email signer in `getOrCreateWallet` on wallet instance.
@crossmint/common-sdk-base

⚠️ Fix issue with email signers and jwt not being set

---

.changeset/eighty-lizards-guess.md
packages/client/ui/react-ui/src/providers/CrossmintAuthProvider.tsx

We weren't setting the jwt on non-email authentications like Twitter so we would then not generate a wallet
Tested with devkit

Auth: Fixes storing jwt after Twitter login

---

.changeset/spicy-tomatoes-relate.md
packages/client/react-base/src/types/wallet.ts
packages/common/base/src/types/signers.ts
packages/wallets/src/signers/solana-external-wallet.ts
packages/wallets/src/signers/types.ts

Typescript types weren't working for when unsupported signer types were passed based on chain passed. For instance, passing `createOnLogin={{ chain: "solana", signer: { type: "passkey" } }}` wasn't throwing a ts error and as you probably know, we don't support passkeys on solana yet. 
closes https://linear.app/crossmint/issue/WAL-4999/signer-types-for-createonlogin-dont-fail-based-on-the-chain
tested that type error throws on react, react native, and just wallets sdk 
@crossmint/common-sdk-base

Signer types vary based on chain (TypeScript)

---

.changeset/lovely-lemons-obey.md
packages/client/react-base/src/providers/CrossmintWalletBaseProvider.tsx
packages/client/ui/react-native/src/providers/CrossmintWalletProvider.tsx
packages/wallets/src/signers/email/email-signer.ts
packages/wallets/src/signers/email/evm-email-signer.ts
packages/wallets/src/signers/email/solana-email-signer.ts
packages/wallets/src/signers/types.ts
packages/wallets/src/wallets/types.ts
packages/wallets/src/wallets/wallet-factory.ts

Move _handshakeParent property from the signer to the options config. Also in CrossmintWalletBaseProvider, rename `_getEmailSignerIframe` to `_getSignerConnection`.
closes https://linear.app/crossmint/issue/WAL-4794/handshakeparent-should-not-be-on-email-signer
ensured that the `_handshakeParent` is no longer on signer and instead in options.
@crossmint/client-sdk-react-native-ui

Move _handshakeParent from signer to options

---

.changeset/great-rice-raise.md
packages/wallets/src/signers/email/email-iframe-manager.ts

Send window.location.origin when starting the iframe handshake
Tested locally, will fully test once the signer iframe is deployed

Add query param to iframe init

---

.changeset/wise-shirts-scream.md
packages/client/react-base/src/providers/CrossmintWalletBaseProvider.tsx
packages/wallets/src/wallets/wallet-factory.ts

Passes `owner` when creating the wallet instance. 
Closes https://linear.app/crossmint/issue/WAL-5180/owner-is-null-even-though-linkeduser-is-set-up
tested owner

Wallets sdk: Owner not being passed to wallet instance

---

.changeset/dry-tomatoes-mix.md
packages/wallets/package.json
packages/wallets/src/openapi.json
packages/wallets/src/wallets/evm.ts
packages/wallets/src/wallets/solana.ts
packages/wallets/src/wallets/types.ts
packages/wallets/src/wallets/wallet.ts
pnpm-lock.yaml

Add new param `options` with `experimental_prepareOnly` that will return an unsigned transaction id if used. 
added to wallet `send` method and evm and solana specific `sendTransaction` methods. 
Closes: https://linear.app/crossmint/issue/WAL-5150/add-preparetransaction-to-solanawallet-and-evmwallet-server-side
Closes: https://linear.app/crossmint/issue/WAL-5179/update-sendtransaction-method-on-evm-with-missing-inputs
new params works on both evm and sol wallet instances. return types also infer based on the options passed for the txn return type.

Wallets sdk: Expose new param options.experimental_prepareOnly on EVM/SOL wallet

---

.changeset/mighty-cougars-think.md
packages/client/window/src/transport/WindowTransport.ts

Context here: https://linear.app/crossmint/issue/WAL-5344/low-missing-eventsource-validation-allows-same-origin-message-spoofing
Manual testing

WAL-5344: Validate both origin AND source

---

.changeset/fair-tomatoes-enjoy.md
packages/client/window/src/windows/NewTab.ts

Revert hosted checkout newtab changes from this commit: 
- https://github.com/Crossmint/crossmint-sdk/commit/99171e9d06a5c498be189d29fae449e6054c6b2d#diff-e9b2847276cd51b6f16d873926afa23f8ad3df047e04295035e4f82075d09938R10-R52
reverting a bug with this string causing a loss of parent frame communication.
@crossmint/client-sdk-window

Revert hosted checkout newtab change

---

.changeset/thin-humans-sort.md
packages/client/window/src/index.ts
packages/client/window/src/transport/SignersWindowTransport.ts
packages/client/window/src/transport/WindowTransport.ts
packages/client/window/src/windows/IFrame.ts
packages/wallets/src/signers/email/email-iframe-manager.ts

We add a specific window transport for our ncs flow, with a tighter security control, as recommended by the auditors.
For context if the current changes were applied to the WindowTransport class, then our social auth flows would break.
Tested e2e ncs flows, and social login flows.

WAL-5344: Harden transport for signers flow

---

.changeset/curly-moles-joke.md
.changeset/smart-planets-look.md
apps/wallets/quickstart-devkit/app/providers.tsx
packages/client/ui/react-native/src/testUtils.ts
packages/client/ui/react-ui/src/components/signers/EmailOTPInput.tsx
packages/client/ui/react-ui/src/hooks/useOAuthWindowListener.ts
packages/client/ui/react-ui/src/testUtils.ts

Our otp styles broke after updating our twind configuration. 
tested styles

Fix: NCS otp ui styles

---

.changeset/hot-ligers-mate.md
.changeset/six-books-vanish.md
apps/wallets/quickstart-devkit/components/approval-test.tsx
packages/client/ui/react-native/src/index.ts
packages/client/ui/react-ui/src/types/wallet.ts
packages/wallets/src/index.ts
packages/wallets/src/wallets/evm.ts
packages/wallets/src/wallets/solana.ts
packages/wallets/src/wallets/stellar.ts
packages/wallets/src/wallets/types.ts
packages/wallets/src/wallets/wallet.ts

- Support correct return type based on input for `approve` method. (closes https://linear.app/crossmint/issue/WAL-5757/approve-to-return-a-different-object-based-on-input)
- Add a `experimental_prepareOnly` option for our existing signature methods (`signTypedData` and `signMessage`). (closes https://linear.app/crossmint/issue/WAL-5526/add-prepareonly-to-signatures)
- tested adding `experimental_prepareOnly` to both signature methods, and expected type is retuned.
- tested approving a signatureId with `approve` and a signature was returned.
- tested approving a transactionId with `approve` and a transaction was returned.
@crossmint/client-sdk-react-native-ui

Wallets SDK: add prepareOnly signatures and fix approve return type

---

packages/wallets/src/signers/non-custodial/ncs-stellar-signer.ts

We moved to a base64 encoding bur didn't update the verification of the public key format
Tested locally

Stellar: fix encode type on sign transaction

---

.changeset/five-fishes-heal.md
packages/client/signers/src/communications/events.ts
packages/client/signers/src/communications/index.ts
packages/client/signers/src/communications/schemas.ts

We want the index and export page to handle different events, so we separate it here. Export should only listen to the export event and it should not be accessible from index.
Tested with the react apps
client-signers: patch

fix: Make export-signer events a specific type 

---

.changeset/seven-dingos-itch.md
apps/wallets/smart-wallet/expo/app/_layout.tsx
packages/client/ui/react-native/src/providers/CrossmintAuthProvider.tsx

The callbackUrl will be the same as the `scheme` that is found within `app.json`.
`https://api.stytch.com/v1/public/oauth/google/start?public_token=public-token-live-f9456a2e-4d5a-494d-baf7-27bdacd8b160&login_redirect_url=https://staging.crossmint.com/api/2024-09-26/session/sdk/auth/authenticate?callbackUrl=myapp%3A%2F%2F&signinAuthenticationMethod=google&apiKey={{apiKey}}&signup_redirect_url=https://staging.crossmint.com/api/2024-09-26/session/sdk/auth/authenticate?callbackUrl=myapp%3A%2F%2F&signinAuthenticationMethod=google&apiKey={{apiKey}}&provider_prompt=select_account`
Testing on android
https://github.com/user-attachments/assets/56a8dcda-ad7f-4457-8df0-ab9283236e47
Testing on ios
https://github.com/user-attachments/assets/0df6bc0c-e4fb-456f-925e-d17e7f3a8b27

React-native app: Adding scheme to auth providers

---

.changeset/fifty-sheep-crash.md
packages/wallets/src/wallets/stellar.ts
packages/wallets/src/wallets/types.ts

Rename `serializedTransaction` parameter to `transaction` in Stellar wallet for consistency with EVM and Solana
SDK builds.
wallets-sdk

feat: rename serializedTransaction parameter to transaction in Stellar

---

.changeset/violet-plums-work.md
packages/client/rn-window/src/rn-webview/RNWebView.tsx
packages/client/window/src/EventEmitter.ts
packages/wallets/src/signers/non-custodial/ncs-signer.ts

Motivation: while doing chaos testing and injecting errors saw how a network failure could lead to an event never properly managed and kept retried forever, casing the user to reach rate limits. This issue motivated these changes
Some improvements
- Detect when the connection is undefined and warn about it
- Add timestamp to logs from the WebView
- Add finite number of retries for failed events, optionally
Will be tested with a sample application

NCS: fix some RN event handling issues

---

.changeset/swift-countries-heal.md
packages/wallets/src/wallets/evm.ts

This was not handled as a smart wallet signature but as a EOA instead, which was not correct
Nothing to test

Fix: EVM typed data signature type

---

packages/client/base/src/types/embed/v3/CrossmintEmbeddedCheckoutV3Props.ts

For Onramp, we need to create the order in the backend and then pass it to embedded for security reasons. So we have to be able to pick up in the frontend an order started in the backend. This was also [recently added to the backend](https://github.com/Paella-Labs/crossbit-main/pull/20855/files#diff-b871b698c4fdafaa5e25949e9b0e05daa02dfd500e6346b504d7c01ecf512582R272) but was missing in the official SDK
Built locally

Onramp: Adding clientSecret attribute to CrossmintEmbeddedCheckoutV3ExistingOrderProps
